[FEATURE] Spring Security 적용
team-go-higher/backend pull request #10
Opened 2023-08-28 07:22 UTC by kyukong

## Issue
- #6 

## 작업 내용
- Spring Security 적용
- Google OAuth2 로그인 적용
  - 사용자 정보 저장

## 다음 PR 에 추가될 기능
- kakao OAuth2 로그인
- JWT 토큰 발급
- 테스트코드 작성
- Security 모듈 분리(고민중)

## 논의할 내용
- application 파일 관리 방식
- 보호되어야 하는 키 값 관리 방식

2023-08-28 07:27 UTC, kyukong commented on core-application/src/main/java/gohigher/usecase/OauthLoginInUseCase.java
> +			.orElseGet(() -> userRepository.save(new User(email, Role.GUEST, provider)));
고하이어 서비스는 가입 후 직무 등 선택해야 하는 정보가 있기 때문에, 직무 선택 창을 띄우기 위해 GUEST 권한을 추가하였습니다.

- GUEST : 가입 완료, 직무 선택 필요
- USER : 가입 완료, 직무 선택 완료
- ADMIN : 어드민 계정

2023-08-28 07:27 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +		System.out.println("됐다!!");
성공 및 실패 등의 과정은 추후 추가할 예정으로 현재는 구현되어 있지 않습니다.

2023-08-28 07:31 UTC, kyukong commented on in-adapter-api/src/main/resources/application.yml
> +      - application-oauth2.yml
oauth2 서버에서 발급받은 키 값은 push 하지 않았습니다.

2023-08-28 07:42 UTC, Seongwon97 requested changes
일단 Security와 OAuth-Client에 대한 학습이 부족하여 눈으로 보이는 코드에 대해서만 피드백을 남겼습니다!! Security와 관련한 것은 조금 학습 후 다시 남겨보겠습니다

2023-08-28 07:42 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/usecase/OauthLoginInUseCase.java
> +@AllArgsConstructor
`@AllArgsConstructor`보다는 `@RequiredArgsConstructor`가 더 좋을 것 같습니다!

2023-08-28 07:42 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/config/SpringSecurityConfig.java
> +@AllArgsConstructor
해당 부분도 final을 붙은 `OauthUserService`와 `AuthenticationSuccessHandler`의 빈을 주입시켜주는 생성자가 필요한 것이라 `@RequiredArgs`가 더 좋을 것 같아요!!

`@AllArgsConstructor`와 `@RequiredArgsConstructor`는 취향같긴한데 한번 이야기해서 통일하면 좋을 것 같습니다!

2023-08-28 07:42 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +@AllArgsConstructor
해당 코드에는 생성자가 필요 없을 것 같아요!

2023-08-28 07:42 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/user/UserRepository.java
> +@Repository
`JpaRepository`를 상속한 것이라 `@Repository` 어노테이션은 제거해도 될 것 같습니다!

2023-08-28 07:42 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/user/UserJpaEntity.java
> +@NoArgsConstructor
기본 생성자의 경우는 열어주는 범위를 Protected로 하여 최소화하는 것은 어떨까요?`@NoArgsConstructor(access = AccessLevel.PROTECTED)`

2023-08-28 07:42 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/user/UserJpaEntity.java
> +	@GeneratedValue
usecase 파트쪽은 `@GeneratedValue(strategy = GenerationType.IDENTITY)`로 GenerationType을 명시하긴했는데 어떤 형태로 하던지 통일을 진행하면 좋을 것 같습니다!

2023-08-28 07:42 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/oauth2/OauthUserService.java
> +	private DefaultOAuth2User createOAuth2User(Map<String, Object> memberAttribute, User loginUser) {
어떤 코드는 argument에 `final` 키워드가 붙고 어떤 코드들은 붙지 않는데 이것도 통일화가 필요할 것 같아요!

팀 코드에 어느 범위까지 final 키워드를 붙일지 이야기를 해봐야 할 것 같네요

2023-08-28 07:46 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/oauth2/OauthUserService.java
> +	private DefaultOAuth2User createOAuth2User(Map<String, Object> memberAttribute, User loginUser) {
넵 이 부분은 사전에 얘기를 나눈 것이 없어 그대로 두었습니다! 이야기 후 적용하도록 하겠습니다!

2023-08-28 07:48 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/config/SpringSecurityConfig.java
> +@AllArgsConstructor
일단 `@RequiredArgsConstructor` 로 변경해두었으나 이야기를 나눠보면 좋을것 같습니다!

2023-08-28 07:56 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/config/SpringSecurityConfig.java
> +@AllArgsConstructor
저는 개인적으로 `final`키워드와 함께 활용할 수 있는 `@RequiredArgsConstructor`를 선호하긴 합니다..ㅎ

2023-08-28 08:04 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/config/SpringSecurityConfig.java
> +@AllArgsConstructor
사실 저도 RequiredArgsConstructor 를 더 선호하나, 예제 코드를 옮기는 과정에 섞여들어간듯 합니다..ㅎㅎㅎㅎ..

2023-08-29 12:22 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/user/UserJpaEntity.java
> +	@GeneratedValue
특별한게 아니면 Identity가 좋은 것 같습니다~!

2023-08-29 14:27 UTC, Byeongju-Kong approved these changes

2023-08-29 14:27 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/usecase/OauthLoginInUseCase.java
> +	private final OauthLoginOutPort userRepository;
여기 필드명이 타입 따라서 가면 좋을 것 같아요!

2023-08-29 14:27 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/port/out/OauthLoginOutPort.java
> +public interface OauthLoginOutPort {
OutPort의 경우에, 해당 포트가 하는 성격(DB 저장, 외부 API 호출 등)이 나오면 좋을 것 같아요!
그래서. 저와 성원님의 경우에 DB와 상호작용하는 것에 대해서는 PersistencePort와 같은 네이밍을 했는데 BE 전체적으로 이야기하면 좋을 것 같네요!

2023-08-29 14:27 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +		System.out.println("됐다!!");
sout은 빼고 머지하는게 좋을 것 같아요! 차라리 주석이 나을 수도..?🤔

2023-08-29 14:27 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/oauth2/OAuth2Attribute.java
> +	}
뭔가 if문 안에 예외를 던지는게 있고 28번째 줄에 return이 있는게 좋은 것 같은데.. 이건 개인적인 생각이니 고려만 해보십숑~!

2023-08-29 14:27 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/oauth2/OAuth2Attribute.java
> +	}
필드가 많지 않은데, Builder를 쓰신 이유가 있을까요?
Builder는 객체가 null 필드를 가진 채로 생성될 가능성이 있어서 위험하다고 생각합니다!

2023-08-29 15:08 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +		System.out.println("됐다!!");
빼야죠!!!

2023-08-29 15:55 UTC, Seongwon97 approved these changes

2023-08-30 06:53 UTC, merged