[FEATURE] 나의 지원서 모아보기 기능 구현
team-go-higher/backend pull request #202
Opened 2024-04-30 09:24 UTC by kyukong

## 작업 내용
- 나의 지원서 모아보기 기능 구현
- 쿼리상으로 구현하기 어렵거나 MySQL 의 함수를 직접 사용해야 하는 경우가 있어 모든 조건을 만족하지는 않습니다.
- 시간이 걸리는 부분은 다음 이슈에서 해결하겠습니다.

## 작업 보충 필요
- 세부 정렬 및 필터링 보완 필요
- 모든 정렬 불가능
  - 전형순, 전형역순 정렬 (X)
  - 마감임박순 정렬 (X)
- 일부 필터링 불가능
  - ProcessType 이 포함된 것만 조회 (O)
  - 마감된것만, 마감되지 않은 것만 (X)
- 검색어 가능
  - 회사명 검색 조회 (O)

resolve #192

2024-04-30 10:44 UTC, shindong96 requested changes
고생하셨습니다 유빈님ㅎㅎ
현재 QueryDsl을 잘 몰라서 일단 네이밍관련 리뷰부터 남겼어요!

그런데 궁금한 부분이 있어요 🤔
지원서 모아보기는 각 지원서의 현재 프로세스에 대해서만 조회하는 방식으로 기획하였습니다.
현재의 코드에 이 부분이 반영되어 있는지를 잘 모르겠어서요ㅠㅠ
반영되어 있다면 어느 부분인지 알려주실 수 있으실까요?

2024-04-30 10:44 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
> +	PagingResponse<MyApplicationResponse> findAllByUserId(Long userId, PagingRequest pagingRequest, MyApplicationRequest request);
메서드 네임이 전부를 가져온다고 해도 될지 잘 모르겠네요...페이징이 들어가서ㅠ 어떻게 생각하시나요?

2024-04-30 10:44 UTC, shindong96 commented on core-domain/src/main/java/gohigher/application/search/ApplicationSortingType.java
> +    RE_SCHEDULED("re-scheduled"),
전형순과 역순이라는 의미라면 `PROCESS_TYPE` 과 `REVERSE_PROCESS_TYPE`은 어떨까요? 현재는 전형일순일 것 같은 느낌이 드는거 같아요 😎

2024-04-30 10:44 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/MyApplicationRequest.java
> +public class MyApplicationRequest {
필터링과 정력에 관한 Request라는 의미가 들어가는 네이밍이 필요할거 같아요!

2024-04-30 10:44 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/MyApplicationRequest.java
> +    private final List<String> scheduled;
```suggestion
    private final List<Boolean> isClosed;
```

closed, unclosed 를 나타내려면 scheduled 보다 isClosed는 어떨까요? 해당 부분에 대한 Column을 isClosed로 나타낼 생각입니다!

2024-04-30 13:00 UTC, kyukong commented on core-domain/src/main/java/gohigher/application/search/ApplicationSortingType.java
> +    RE_SCHEDULED("re-scheduled"),
넵 반영하겠습니다!!!

2024-04-30 13:11 UTC, kyukong commented on core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
> +	PagingResponse<MyApplicationResponse> findAllByUserId(Long userId, PagingRequest pagingRequest, MyApplicationRequest request);
으음.. 파라미터에도 페이징 변수가 있고 메서드명에 모든 것을 설명할 필요는 없다고 생각합니다! 혹시 평소에 페이징 기능이 있는 메서드의 네이밍은 어떻게 하셨는지 알 수 있을까요?

2024-04-30 13:11 UTC, kyukong commented on core-application/src/main/java/gohigher/application/port/in/MyApplicationRequest.java
> +public class MyApplicationRequest {
메서드 네이밍이 정해지면 같이 따라가겠습니다!

2024-05-01 06:56 UTC, kyukong commented
> 고생하셨습니다 유빈님ㅎㅎ 현재 QueryDsl을 잘 몰라서 일단 네이밍관련 리뷰부터 남겼어요!
> 
> 그런데 궁금한 부분이 있어요 🤔 지원서 모아보기는 각 지원서의 현재 프로세스에 대해서만 조회하는 방식으로 기획하였습니다. 현재의 코드에 이 부분이 반영되어 있는지를 잘 모르겠어서요ㅠㅠ 반영되어 있다면 어느 부분인지 알려주실 수 있으실까요?

아앗 현재 전형만 추가하는 거였군요..!! 바로 추가했습니다.
ApplicationRepositoryCustomImpl#findAllByUserId 의 where 절에 추가했고, 관련 테스트도 추가했습니다.

2024-05-07 01:30 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
> +	PagingResponse<MyApplicationResponse> findAllByUserId(Long userId, PagingRequest pagingRequest, MyApplicationRequest request);
해본적이 없네요ㅠㅠ변수가 있으니 그냥 사용해도 좋을 거 같기두 하네요ㅎㅎ

2024-05-07 01:36 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +	private <T> List<T> findApplicationsByUserId(List<Application> applications, BiFunction<Application, Process, T> responseMapper) {
BiFunction!!

2024-05-07 01:49 UTC, kyukong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +	private <T> List<T> findApplicationsByUserId(List<Application> applications, BiFunction<Application, Process, T> responseMapper) {
입력과 출력의 타입만 다르고 로직이 동일하여 함수형 인터페이스 이용해서 공통 부분 추출했습니다.. 혹시 문제가 되는 지점이 있을까요? 🥲

2024-05-07 01:59 UTC, shindong96 approved these changes
수고하셨습니다 유빈님! 우선 머지하구 차후에 업그레이드 시켜나가요!

2024-05-07 02:00 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +	private <T> List<T> findApplicationsByUserId(List<Application> applications, BiFunction<Application, Process, T> responseMapper) {
아니요! 너무 좋은거 같아서요ㅎㅎ

2024-05-07 02:00 UTC, merged