[FEATURE]
team-go-higher/backend pull request #25
Opened 2023-09-03 09:04 UTC by shindong96

## 작업 내용
- Spring Security를 통해 Oauth 인증에 성공하면 Access, Refresh 토큰을 발급해줍니다.
- Security에 JwtFilter를 추가해 소셜 인증 전에 토큰 인증을 진행합니다.

resolve #15

2023-09-03 11:16 UTC, kyukong requested changes
안녕하세요! 내용도 많고 어려웠던 파트인데 고생많으셨습니다! 👏🏻
혹시 암호화된 application-jwt.yml 은 아직 업로드되지 않은 걸까요??

2023-09-03 11:16 UTC, kyukong commented on core-application/src/main/java/gohigher/usecase/OAuth2QueryService.java
> +			.orElseThrow(IllegalAccessError::new);
GoHigherException 을 발생시키는건 어떨까요??

2023-09-03 11:16 UTC, kyukong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			throw new JwtException("Access Token Expired");
ControllerAdvice 전에 발생하는 예외더라도, success, error, data 등 에러 규칙이 통일되는 편이 프론트 쪽에서 관리하기 쉬울것 같습니다!

2023-09-03 11:16 UTC, kyukong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
ROLE_ 은 OauthUserService 에서도 사용되는 문자열인데, 사용자 객체 내부에서 관리하면 어떨까요?

2023-09-03 11:16 UTC, kyukong commented on security/src/main/java/gohigher/jwt/support/AuthorizationExtractor.java
> +	private AuthorizationExtractor() {
롬복 어노테이션을 써도 좋을것같습니다!!

2023-09-03 11:16 UTC, kyukong commented on security/src/main/java/gohigher/jwt/support/CookieProvider.java
> +	private final long refreshTokenExpireLength;
```suggestion
	private static final String REFRESH_TOKEN = "refreshToken";
	
	private final long refreshTokenExpireLength;
```

가독성 및 용도의 구분을 위해 띄워주면 어떨까요? 그리고 상수 이름으로 REFRESH_TOKEN 은 리프레시 토큰 자체를 의미하는 느낌이 더 큰것 같은데 KEY_OF_REFRESH_TOKEN 이나 REFRESH_TOKEN_KEY 등의 이름은 어떠신가요??

2023-09-03 11:16 UTC, kyukong commented on security/src/main/java/gohigher/oauth2/AuthenticationFailureHandler.java
> +		response.sendError(HttpServletResponse.SC_UNAUTHORIZED);
여기도 응답 형식을 맞추는 편이 좋을것 같습니다!

2023-09-03 11:16 UTC, kyukong commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +	private final String redirectUrl = "http://localhost:3000/token";
이 값은 설정값에서 관리하면 어떨까요? 다른 코드에서 같이 사용되는 `/token` 도 yml 에서 관리하면 휴먼에러를 방지할 수 있을것 같아요!

2023-09-03 11:16 UTC, kyukong commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +			.orElseThrow(IllegalAccessError::new)
여기도 GoHigherException 을 발생시키는건 어떨까요?? 🤔

2023-09-03 11:16 UTC, kyukong commented on security/src/test/java/gohigher/support/JwtProviderTest.java
> +		JwtProvider jwtProvider = new JwtProvider(SECRET, ACCESS_TOKEN_EXPIRE_LENGTH, REFRESH_TOKEN_EXPIRE_LENGTH);
`@BeforeEach` 로 객체를 생성하는건 어떨까요??

2023-09-03 12:58 UTC, Seongwon97 approved these changes
수고하셨습니다!!!
컨벤션과 개인적으로 궁금한 내용을 코멘트로 남겼습니다!!
확인 부탁드립니다👍

2023-09-03 12:58 UTC, Seongwon97 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +
공백 라인이 두 줄이 있네요!

2023-09-03 12:58 UTC, Seongwon97 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			throw new JwtException("Access Token Expired");
spring boot를 사용하더라도 Filter에서 예외가 발생하면 ControllerAdvice가 예외를 못 잡나요?? (궁금해서 물어봅니다..)

2023-09-03 12:58 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/usecase/OAuth2QueryService.java
> +
불필요한 공백라인인것 같습니다!!

2023-09-03 12:58 UTC, Seongwon97 commented on security/src/main/java/gohigher/jwt/JwtExceptionFilter.java
> +		}
이때는 servlet에서 지정한 body가 없이 status code만 있는 Response의 결과가 반환되는 걸까요..?

2023-09-03 13:01 UTC, kyukong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			throw new JwtException("Access Token Expired");
Controller 로 넘어온 이후에야 ControllerAdvice 가 캐치할 수 있어, Filter 의 예외는 접근하지 못하는 걸로 알고 있습니다! 그래서 사례들을 찾아보니 예외가 발생할 수 있는 Filter 앞에 예외 처리하는 Filter 를 직접 정의하는 방식으로 처리하는듯해요.

2023-09-03 13:07 UTC, Byeongju-Kong requested changes
out-adapter-persistence 모듈에 OAuth2Repository에서 OAuth2라는 네이밍이 빠지면 좋을 것 같습니다! User의 의미만 들어가면 어떨까요? 또한, OAuth2Repository는 노션에서 정한 port-adapter 네이밍들로 변경되야하고 query와 command가 나뉘어야 할 것 같네요!

그리고 OAuth2CommandPort, OAuth2QueryPort의 경우에도 UserCommandPort와 UserQueryPort라는 네이밍으로 변경하는 것에 대해 어떻게 생각하시나요?
이 부분은 저도 지금 감이 잘 안와서 다같이 이야기해봐야할 것 같네요!

2023-09-03 13:07 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/jwt/support/JwtProvider.java
> +	}
subject에 email을 넣으신 이유가 있나요?
제 생각에는 userId는 필요하다고 생각합니다!

만약, token에 email 값만 담기게 된다면, Controller에서는 email만을 사용할 수 있고
Service 로직에서 userId가 필요하다면 DB 조회를 한번 해야하는 상황이 생길 것 같네요 😢

userId가 필요한 예시로, 지원서 작성 등의 경우에 지원서 테이블에 userId를 FK로 갖기 때문에 로직상 userId가 반드시 필요합니다!

2023-09-03 13:07 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			throw new JwtException("Access Token Expired");
이 부분 분기가 반대로 되어있는지에 대한 의문이 듭니다!
verifyToken 메서드를 보면, token의 expiration.after(now)라고 되어 있는데, true가 반환된다면 토큰의 만료시간이 지났다고 이해했는데요.  !jwtProvider.verifyToken() 에서 ! 로 인하여 로직이 뒤집힌거 아닌가요..?

제가 헷갈린 걸 수도 있으니 한번 검토해주시길 바랍니다!

2023-09-03 13:07 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +	}
메서드가 너무 긴 것 같습니다!

2023-09-03 14:03 UTC, shindong96 commented on core-application/src/main/java/gohigher/usecase/OAuth2QueryService.java
> +			.orElseThrow(IllegalAccessError::new);
Pull 이후에 안고쳤네요ㅜㅜ 반영하겠습니다!

2023-09-03 14:07 UTC, shindong96 commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +	private final String redirectUrl = "http://localhost:3000/token";
혹시 SecurityCongfig를 얘기하시는 걸까요?

2023-09-03 15:05 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			throw new JwtException("Access Token Expired");
expiration이 만료되는 날짜라서 `만료 날짜가 오늘보다 뒤이면 true가 반환`됩니다! 즉, true이면 아직 토큰이 남았다는 의미입니다! :)

2023-09-03 15:06 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/support/JwtProvider.java
> +	}
넵!! 저도 동의합니다ㅎㅎ
변경하였습니다!

2023-09-03 15:08 UTC, kyukong commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +	private final String redirectUrl = "http://localhost:3000/token";
application.yml 을 의미했습니다! token 을 발급받는 url 이 여러 곳에서 관리되어 한곳에서 관리하면 좋을듯하여 남겨봤습니다! ㅎㅎ

2023-09-03 15:45 UTC, shindong96 commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +	}
줄여보겠습니다!

2023-09-03 15:49 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +
수정하겠습니다!ㅜㅜ

2023-09-03 15:49 UTC, shindong96 commented on core-application/src/main/java/gohigher/usecase/OAuth2QueryService.java
> +
지우겠습니다!

2023-09-03 15:51 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/JwtExceptionFilter.java
> +		}
Response 컨벤션아 생기기 전인데 고치지 않았네요ㅜㅜ
body가 넘어가게 수정하였습니다.
그런데 현재 GoHigherResponse가 in-adapter 모듈에 있어 해당 모듈에도 똑같이 생긴 Response가 추가되었습니다ㅜ
더 좋은 방법이 있을까요?

2023-09-03 15:52 UTC, shindong96 commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +			.orElseThrow(IllegalAccessError::new)
이 부분은 좋은 방법이 떠오르지 않네요ㅜㅜ저기서 에러가 발생하면 사실상 서버 에러인데  혹시 생각하시는 방법이 있으실까요?

2023-09-03 16:01 UTC, shindong96 commented on security/src/main/java/gohigher/oauth2/AuthenticationFailureHandler.java
> +		response.sendError(HttpServletResponse.SC_UNAUTHORIZED);
넵 수정해보겠습니다!

2023-09-03 16:01 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
아예 테이블에 ROLE_USER 이런식으로 말씀이실까요?

2023-09-03 16:27 UTC, shindong96 commented on security/src/test/java/gohigher/support/JwtProviderTest.java
> +		JwtProvider jwtProvider = new JwtProvider(SECRET, ACCESS_TOKEN_EXPIRE_LENGTH, REFRESH_TOKEN_EXPIRE_LENGTH);
좋아요!

2023-09-03 18:06 UTC, shindong96 commented
누락된 부분이 있어 추가 수정하였습니다!!
리뷰 부탁드려요!

2023-09-04 03:04 UTC, kyukong requested changes
새로 추가된 부분들에 약간의 피드백을 남겨봤습니다~ 고생하셨어요!

2023-09-04 03:04 UTC, kyukong commented on core-domain/src/main/java/gohigher/user/UserErrorCode.java
> +
```suggestion
```
공백라인이 2개 들어갔네요!

2023-09-04 03:04 UTC, kyukong commented on core-domain/src/main/java/gohigher/user/UserErrorCode.java
> +	USER_NOT_EXISTS(404, "USER_001", "존재하지 않는 사용자입니다."),
`404` 는 페이지를 찾을 수 없는 것에 더 가까운거같은데, `400` 번은 어떠신가요?

2023-09-04 03:04 UTC, kyukong commented on core-application/src/main/java/gohigher/usecase/UserCommandService.java
> +			.orElseGet(() -> userPersistenceCommandPort.save(new User(email, Role.GUEST, provider)));
`User.login(...)` 처럼 정적 팩토리 메서드로 만드는건 어떤가요? 의미가 더 명확해질것 같습니다! 이건 저의 스타일이니 꼭 반영하지 않으셔도 됩니당..

2023-09-04 03:04 UTC, kyukong commented on core-domain/src/main/java/gohigher/user/UserErrorCode.java
> +package gohigher.user;
전에는 exception 패키지에 몰아넣는걸 말씀드렸는데, 막상 구현된걸 보니 도메인 별 패키지도 괜찮네요 ㅎㅎㅎ

2023-09-04 03:04 UTC, kyukong commented on core-domain/src/main/java/gohigher/user/User.java
User 객체 생성자에도 final 제거 부탁드립니다! ㅎㅎ

2023-09-04 03:04 UTC, kyukong commented on security/src/main/java/gohigher/AuthErrorCode.java
> +	INVALID_OAUTH_RESPONSE(401, "AUTH_010", "소셜 로그인 실패입니다."),
errorCode  범위 기준을 주석으로 남겨두면 어떨까요?

2023-09-04 03:04 UTC, kyukong commented on security/src/main/java/gohigher/AuthErrorCode.java
> +package gohigher;
도메인 모듈에 user > oauth2 를 user > auth 로 변경 후 auth 내부로 이동시키는건 어떨까요?

2023-09-04 03:04 UTC, kyukong commented on security/src/main/java/gohigher/response/GoHigherResponse.java
> +public class GoHigherResponse<T> {
`ErrorResponse` 와 `GoHigherResponse` 가 security 모듈에서 in 모듈에 접근하지 않기 위해 추가된 것이 맞을까요? security 모듈에는 exception 을 throw 만 시키고, in 모듈에 최상위 filter 를 정의하여 모든 exception 을 받는 것을 처리하면 어떨까요?

2023-09-04 03:08 UTC, kyukong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
아뇹! User 객체 내부에 상수로 관리하자는 의견이었습니다! ROLE_ 문자열이 쓰이는 곳이 prefix 를 추가하는 로직이기 때문에, 해당 메서드로 만들어도 좋을것같아요.

```java
user.concatRole();
```

메서드 네이밍은 변경하셔도 됩니당..

2023-09-04 03:16 UTC, kyukong commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +	private final String redirectUrl = "http://localhost:3000/token";
제가 질문의 의미를 잘 파악하지 못했던거같아 다시 답글 남깁니다...!! `/token` 경로가 토큰을 발급받기 위한 경로가 맞을까요? 맞다면 경로 변경 시 다른 곳에서도 변경이 발생할 수 있을것같아서 남겼습니다!

설명해주신 2번과 3번의 경우 코드가 사용하는 곳에서의 의미는 다르지만, 가리키는 값은 같다고 생각했어요. (1번은 정확히 어떤 의미로 사용되는 값인지 잘 모르겠네요ㅠㅠ)

2023-09-04 03:21 UTC, kyukong commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +			.orElseThrow(IllegalAccessError::new)
저는 GoHigherException 이 상태코드에 관계없이, 저희 프로그램 내부에서 발생한 예외만 필터링하기 위해 사용된다고 이해했어요. 그래서 500번대 에러라도 GoHigherException 을 발생시키고 적절한 상태코드를 부여할듯하네요!

2023-09-04 03:45 UTC, Seongwon97 commented on security/src/main/java/gohigher/AuthErrorCode.java
> +	INVALID_OAUTH_RESPONSE(401, "AUTH_010", "소셜 로그인 실패입니다."),
저도 관리를 위해 클래스 상단에 범위를 남겨두면 좋을 것 같습니다!!

2023-09-04 03:58 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
저는 고민이 되는게 `ROLE_`을 붙이는게 도메인이 알아야하는 부분인가라는 생각이 들어요ㅜㅜ 해당 부분은 도메인보다는 security에 책임이 가까운 부분이라...어떻게 생각하시나요

2023-09-04 04:00 UTC, shindong96 commented on core-domain/src/main/java/gohigher/user/UserErrorCode.java
> +	USER_NOT_EXISTS(404, "USER_001", "존재하지 않는 사용자입니다."),
user_id는 있는데 없는 사용자라 404가 더 알맞지 않을까라 생각했는데 400도 그런 의미를 내포할 수 있을까요?

2023-09-04 04:09 UTC, kyukong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
맞는 말인것 같습니다 :) 그렇다면 security 모듈 내부에서 사용하는 oauth 사용자 객체 또는 역할을 관리하는 객체를 만들어서 관리하는건 어떨까요? 순수 문자열 그대로 여러 곳에서 사용하는 것은 변경 시 취약하기도 하고, 의미 또한 명확하게 드러내기 어렵다고 생각해요.

2023-09-04 04:12 UTC, kyukong commented on core-domain/src/main/java/gohigher/user/UserErrorCode.java
> +	USER_NOT_EXISTS(404, "USER_001", "존재하지 않는 사용자입니다."),
404 는 서버 관점에서 리소스가 없는 경우를 의미한다고 생각해요. 근데 이 리소스는 도메인에 종속적인(ex. 사용자) 리소스가 아닌 서버 자체의 리소스이기 때문에 페이지(url)에 한정되어 있다고 이해했어요. 근데 이건 저의 개인적인 생각이니 다른 분들의 의견도 들어보면 좋을것같아요!

@Byeongju-Kong @Seongwon97

2023-09-04 06:25 UTC, shindong96 commented on core-application/src/main/java/gohigher/usecase/UserCommandService.java
> +			.orElseGet(() -> userPersistenceCommandPort.save(new User(email, Role.GUEST, provider)));
저는 생성자 이외에는 정적 팩토리 메서드를 잘 사용하지 않아봤습니다!
그리고 제가 잘 모르는데 해당 클래스는 인터페이스의 구현체인데 혹시 정적 팩토리 메서드가 가능한가요? 이 부분을 static으로 메서드 내부 메서드들도 static으로 하여야해서 조금 복잡해질 수 있을 거 같아요ㅜㅜ어떻게 생각하시나요?

2023-09-04 06:26 UTC, shindong96 commented on core-domain/src/main/java/gohigher/user/User.java
그러네요ㅜㅜ결국 놓쳤다...

2023-09-04 06:28 UTC, shindong96 commented on core-domain/src/main/java/gohigher/user/UserErrorCode.java
> +
😅

2023-09-04 06:31 UTC, shindong96 commented on security/src/main/java/gohigher/response/GoHigherResponse.java
> +public class GoHigherResponse<T> {
네 말씀하신 의도가 맞아요 :)
그런데 말씀하신 방법으로 하게 되면 security가 in 모듈을 거치지 않는 로그인 기능의 경우 잡아낼 수가 없을거 같아요ㅜㅜ

2023-09-04 06:34 UTC, shindong96 commented on security/src/main/java/gohigher/AuthErrorCode.java
> +package gohigher;
저도 이 생각을 하고 oauth2 패키지를 열었더니 Provider가 있더라구요. 저는 Provider가 oauth라는 패키지 네임에 맞다고 생각돼서 뒀는데  auth로 바꿔도 괜찮을까요?? 저는 찬성이긴 합니다!

2023-09-04 08:01 UTC, kyukong commented on core-application/src/main/java/gohigher/usecase/UserCommandService.java
> +			.orElseGet(() -> userPersistenceCommandPort.save(new User(email, Role.GUEST, provider)));
```java
@RequiredArgsConstructor
@Getter
public class User {

	private final String email;
	private final Role role;
	private final Provider provider;
	private Long id;

	public User(Long id, String email, Role role, Provider provider) {
		this.id = id;
		this.email = email;
		this.role = role;
		this.provider = provider;
	}
	
	public static User join(Long id, String email, Provider provider) {
		return new User(id, email, Role.GUEST, provider);
	}
}
```

User 객체 말씀하시는 것이 맞을까요?? 회원가입 시 역할을 GUEST 로 설정하는 로직을 도메인에서 결정하는 것이 좋을것같아 남긴 의견이었습니다!

2023-09-04 08:03 UTC, kyukong commented on security/src/main/java/gohigher/AuthErrorCode.java
> +	INVALID_OAUTH_RESPONSE(401, "AUTH_010", "소셜 로그인 실패입니다."),
주석은 11번부터 20번까지인데, 코드는 AUTH_010 번이군요!

2023-09-04 08:05 UTC, kyukong commented on security/src/main/java/gohigher/AuthErrorCode.java
> +package gohigher;
Provider 는 oauth 에 더 종속적이긴 하나, 현재 oauth 관련 객체가 Provider 하나뿐이니 수정된 지금 형태로도 괜찮을것 같습니다! 만약 oauth 관련 객체가 추가된다면 user > auth > oauth 등으로 더 상세하게 나눌듯해요.

2023-09-05 01:31 UTC, shindong96 commented on core-application/src/main/java/gohigher/usecase/UserCommandService.java
> +			.orElseGet(() -> userPersistenceCommandPort.save(new User(email, Role.GUEST, provider)));
아! 생성자 말씀이시군요! 좋습니다!!반영하겠습니다!

2023-09-05 01:34 UTC, shindong96 commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +	private final String redirectUrl = "http://localhost:3000/token";
좋은 것 같습니다!!

2023-09-05 02:03 UTC, shindong96 commented on security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
> +			.orElseThrow(IllegalAccessError::new)
500을 던지는게 조금 어색한 것 같아서 일단 GlobalErrorCode를 반환하게 바꿨습니다!

2023-09-05 02:19 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
RoleGrantAuthoriity 객체를 만들었습니다!

2023-09-05 03:06 UTC, kyukong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
```java
	@Serial
	private static final long serialVersionUID = SpringSecurityCoreVersion.SERIAL_VERSION_UID;
	private static final String ROLE_PREFIX = "ROLE_";
```

serialVersionUID 에 `@Serial` 을 붙여주는건 어떨까요? 컴파일 시 직렬화 관련 메서드 오버라이딩을 체크해준다고 합니다.

![image](https://github.com/team-go-higher/backend/assets/92148749/38fb9666-3aba-48e1-bf63-6684cab821d4)

2023-09-05 03:47 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +			List.of(new SimpleGrantedAuthority("ROLE_".concat(user.getRole().toString()))));
반영했습니다ㅎㅎ

2023-09-05 04:46 UTC, Byeongju-Kong approved these changes
고생하셨어요! Approve 할게요~!

2023-09-05 06:01 UTC, kyukong approved these changes
너무너무 고생 많으셨습니다~~~~ 👍👍👍

2023-09-05 06:15 UTC, merged

2023-09-05 06:22 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/port/in/UserCommandPort.java
> +
`core-application` 모듈 내에서도 도메인별로 패키지를 분리하는 것은 어떨까요??

```
gohigher
   ├ application
   └ user
       ├ port
       └ usecase
```
이런 느낌으로요..!!