[FEATURE] Login된 유저들의 Token에서 식별자를 가져온다
team-go-higher/backend pull request #29
Opened 2023-09-03 18:07 UTC by shindong96

## 작업 내용
- 작업한 내용을 정리한다.

resolve #{issue}

2023-09-04 03:55 UTC, Seongwon97 commented
저도 남겨주신 내용에 대해 동의합니다!! 
Security는 메인이 Spring Context외부의 Filter에서 동작하는 것이기에, 애플리케이션 로직 처리를 위해 Header로부터 사용자 정보를 받아오는 Resolver는 api에도 위치하는게 좋을 것 같습니다!
중복 로직이긴하나 둘이 가지는 책임이 다르다고 생각하면 어느정도 허용할 수 있을 것 같습니다!!

그리고 이전 PR의 커밋 기록까지 있어서 해당 PR 코드에 대한 리뷰가 살짝 어려운 것 같습니다!!
이전 PR이 머지된다면 rebase하고 force push를 한번 해주시면 리뷰하기 더 편할 것 같아요!!

2023-09-04 04:28 UTC, Byeongju-Kong requested changes
리뷰 남겨두었습니다~! 고생하셨어요!
지역번수 final에 대해 전반적으로 한번만 체크바랍니당~!

2023-09-04 04:28 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/usecase/token/JwtCommandService.java
> +public class JwtCommandService implements TokenCommandPort {
해당 클래스가 core에 존재하는데요! 
저희가 아키텍처를 설계할 때 core에는 java, 그리고 Spring에서 유용한 의존성 몇개만 가져와서 사용하기로 했었지요!

그런데, 지금 core에 Jwt 의존성이 들어갔네요! 제 생각에는 `jwt의 경우에는 out-adapter 쪽으로 빠지는게 맞지 않은가`라는 생각이 듭니다! 이건 `팀원들이랑 함께 이야기` 해보면 좋을 것 같네요! token이라는 패키지가 jwt 모듈로 빠져도 좋겠다는 생각이 듭니다~!

2023-09-04 04:28 UTC, Byeongju-Kong commented on core-application/src/main/resources/application-jwt.yml
> +    secret-key: ENC(kmdkmc5zMo8nXTqF7f3w2iwCiVv1iwIG77jgbgwnUPsfqkLYwjZ34ZEGLY6YiXd/qsAChzW0TInQlQmVJ+p6YhxBVo/jrIip/Mmwhv6UXifUKaTTbCgYwKtKbVp2JEX+5zv9eh7UHP/h3p1vsepOhUQoDLZ5JTc/JWid8C8FO6LPbbF3yRw
Good!

2023-09-04 04:28 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +		"1b5f8fb17f30171fdc794a47e35d284e0ef047c90a09571b2a3914eb5c0cd1e798d5d4a8a0b8f295dc4588a9e3d87907fed168e32348c56a346a8f1ada76b82e";
이건 사소한건데, 해당 상수는 테스트를 위한 값이라서 임의의 값이고 이렇게 길 필요가 있나 라는 생각이 들어요 🤔😂

2023-09-04 04:28 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +	}
JwtCommandService를 @BeforeEach를 통해 생성하신 이유가 있을까요?

2023-09-04 04:28 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +				new Date(now.getTime() + ACCESS_TOKEN_EXPIRE_LENGTH - UNIT_TO_CONVERT_MILLI_TO_SECOND))).isTrue()
코드 라인이 길어지면 `ACCESS_TOKEN_EXPIRE_LENGTH - UNIT_TO_CONVERT_MILLI_TO_SECOND`을 따로 빼는건 어떨까요?

2023-09-04 04:28 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +				new Date(now.getTime() + ACCESS_TOKEN_EXPIRE_LENGTH - UNIT_TO_CONVERT_MILLI_TO_SECOND))).isTrue()
이건 제가 코드의 가로 길이가 체크가 안되서 남긴 리뷰 입니다! 가로 길이 기준을 넘지 않으면 현 상태로 두셔도 될 것 같아요!

2023-09-04 04:28 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		@RequestParam("userId") Long userId, @RequestParam("role") String role) {
GetMapping 후에 ()가 있네요!

그리고 userId와 role이 requestParam으로 들어오는 이유는 OAuth의 특성인가요? 아니면 API를 직접 설계하신건가요?
직접 설계하신 거라면 RequestBody가 아닌 RequestParam으로 값을 받으신 이유가 있나요?

2023-09-04 04:28 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/auth/support/LoginArgumentResolver.java
> +	}
지역변수에 final이 들어갔네요!

2023-09-04 04:28 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/auth/support/RefreshTokenCookieProvider.java
> +	}
httpOnly, Secure 👍🏻

2023-09-04 04:28 UTC, Byeongju-Kong commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +			REFRESH_TOKEN_EXPIRE_LENGTH);
개행이 없어도 될 것 같아요!

2023-09-04 04:28 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/user/UserPersistenceCommandAdapter.java
> +		final UserJpaEntity savedUser = userRepository.save(UserJpaEntity.from(user));
final!

2023-09-04 04:28 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/jwt/JwtAuthFilter.java
> +	}
여기 메서드를 쪼갤 수 있으면 쪼개는게 좋지 않을까하는 생각입니다!
괜찮다고 판단이 되시면 놔두셔도 됩니다~!

2023-09-04 04:28 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/jwt/support/AuthorizationExtractor.java
> +public class AuthorizationExtractor {
AuthorizationExtractor가 in-adapter에도 있고 security에도 있는데요!
둘다 필요해서 선언하신건가요? 제가 Security와 OAuth2의 로직을 잘 몰라서 궁금하네요!

2023-09-04 04:28 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
> +		return (Long)attributes.get(USER_ID);
```suggestion
		return (Long) attributes.get(USER_ID);
```

2023-09-04 04:28 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/oauth2/user/OAuth2UserInfoFactory.java
> +		}
switch~case 코드가 꽤 잘 읽히네요..? 우테코 때 왜 쓰지 말라한거였죠?

2023-09-04 04:28 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/oauth2/user/OAuth2UserInfoFactory.java
> +		}
아 else 때문에 쓰지말라고 했던거였군요!

2023-09-04 06:39 UTC, Byeongju-Kong requested changes

2023-09-04 06:39 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/auth/support/AuthenticationPrincipal.java
> +}
이거 간단하게 Login 이라고 사용하는건 어떤가요?

2023-09-04 06:46 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +			REFRESH_TOKEN_EXPIRE_LENGTH);
엇 저는 컨벤션이 이렇게 잡아주는데 혹시 아닌가요?

2023-09-04 06:47 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/user/UserPersistenceCommandAdapter.java
> +		final UserJpaEntity savedUser = userRepository.save(UserJpaEntity.from(user));
😱

2023-09-04 06:47 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/support/LoginArgumentResolver.java
> +	}
😥

2023-09-04 06:49 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		@RequestParam("userId") Long userId, @RequestParam("role") String role) {
Oauth가 성공하게 되면 redirect를 시키는 방법을 사용하기에 RequestParam을 사용하게 되었습니다!

2023-09-04 06:52 UTC, shindong96 commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +		"1b5f8fb17f30171fdc794a47e35d284e0ef047c90a09571b2a3914eb5c0cd1e798d5d4a8a0b8f295dc4588a9e3d87907fed168e32348c56a346a8f1ada76b82e";
JwtCommandService의 생성자에서 임의대로 짧게 값을 넣게 되면 아래와 같은 문구가 뜨며 오류가 납니다.

`The specified key byte array is 48 bits which is not secure enough for any JWT HMAC-SHA algorithm.`

그래서 어느 정도의 비트수가 빌표한 것 같아 실제처럼 만들어 보았습니다!

2023-09-04 06:53 UTC, shindong96 commented on core-application/src/main/java/gohigher/usecase/token/JwtCommandService.java
> +public class JwtCommandService implements TokenCommandPort {
그러네요...코어의 의미를 잠깐 잊었군요ㅜㅜ다시 생각해봐야겠네요...

2023-09-04 06:58 UTC, shindong96 commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +	}
@BeforeEach 없이 애초에 필드를 채워도 될거 같아요!

2023-09-04 07:01 UTC, shindong96 commented on security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
> +		return (Long)attributes.get(USER_ID);
Naver 컨벤션 적용 중인데 `(Long)attributes.get(USER_ID);`로 뜨네요. 혹시 제 것만 그런가요?

2023-09-04 07:01 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/support/AuthenticationPrincipal.java
> +}
좋아요!

2023-09-04 08:11 UTC, kyukong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +		"1b5f8fb17f30171fdc794a47e35d284e0ef047c90a09571b2a3914eb5c0cd1e798d5d4a8a0b8f295dc4588a9e3d87907fed168e32348c56a346a8f1ada76b82e";
그래서 전 예전에 String 의 repeat 를 애용했었습니다... 참고해주세요!

2023-09-04 08:14 UTC, kyukong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +	}
전부 상수값이라 현재는 의미가 없지만, 매 테스트마다 새로운 객체로 테스트한다는 취지로 피드백을 남겼었습니다! 지금처럼 필드로 관리할 경우 final 을 붙여도 될것같아요.

2023-09-04 08:15 UTC, kyukong commented on security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
> +		return (Long)attributes.get(USER_ID);
저도 코드 정리 시 공백이 사라집니다. 인텔리제이 설정을 찾아보니 해당 공백에 대한 컨벤션은 Naver 와는 별도인것 같아, 저희끼리 정하면 될듯해요~!

2023-09-04 08:29 UTC, kyukong requested changes
jwt 위치가 아직 확정되지 않아 Request Changes 로 남겼습니다!

그리고 PR 을 남겨주실 때 중점적으로 보면 좋을 것들은 코멘트로 남겨주시면 좋을것같아요. 커밋 로그를 볼 때도 있는데 여러 개의 PR 이 같이 진행되다보니 커밋 로그가 길어져 파악하기 어렵네요ㅜㅜ

고생하셨습니다!

2023-09-04 08:29 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +			GohigherResponse.success(new TokenResponse(accessToken, role)));
해당 로직은 Service 에 두면 어떨까요? Controller 에서 Service 의 역할을 하고 있는것 같아요.

2023-09-04 12:57 UTC, shindong96 commented on security/src/main/java/gohigher/jwt/support/AuthorizationExtractor.java
> +public class AuthorizationExtractor {
둘 군데서 다 필요합니다! 그런데 둘 다 외부 어뎁터라 의존성을 없애려니까 중복 코드가 생기더라구요ㅜㅜ

2023-09-04 13:00 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +			GohigherResponse.success(new TokenResponse(accessToken, role)));
Response는 Service에서 만들어서 올릴 수 있는데 HttpCookie의 경우 헤더에 추가하는 부분이라 서비스 영역보다는 컨트롤러 영역이 맞다고 생각해서 뺐는데 어떻게 생각하시나요??

2023-09-05 02:57 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +			GohigherResponse.success(new TokenResponse(accessToken, role)));
으음.. Response 를 서비스로 끌고가는 것도 역할에 어긋나는듯하고.. 어렵네요ㅠ 일단 유지하는 것이 좋을것같습니다!

2023-09-05 04:48 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +		"1b5f8fb17f30171fdc794a47e35d284e0ef047c90a09571b2a3914eb5c0cd1e798d5d4a8a0b8f295dc4588a9e3d87907fed168e32348c56a346a8f1ada76b82e";
그렇다면 유빈님 의견대로 진행하셔도 될 것 같습니다. 개인적으론, 이유가 있다면 현 상태로 두어도 될 것 같네요~!

2023-09-05 04:49 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/token/JwtCommandServiceTest.java
> +	}
저희가 사용하는 `빈들은 상태 값을 가지고 있지 않기 때문에`, 테스트 마다 새로운 객체를 생성하는 비용이 불필요하다고 생각이 듭니다~!
저는 필드 선언 할 때, 초기화까지 하면 좋을 것 같습니다~!

2023-09-05 04:49 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		@RequestParam("userId") Long userId, @RequestParam("role") String role) {
넵! 답변 감사합니다~! 인지하고 있겠습니다~!

2023-09-05 04:50 UTC, Byeongju-Kong commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +			REFRESH_TOKEN_EXPIRE_LENGTH);
그렇다면 무시하도 됩니다~!

2023-09-05 04:50 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/jwt/support/AuthorizationExtractor.java
> +public class AuthorizationExtractor {
이 부분은 어떻게 해야할지 함께 고민해보아요~! 논의사항으로 등록해두겠습니다!

2023-09-05 04:52 UTC, Byeongju-Kong commented on security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
> +		return (Long)attributes.get(USER_ID);
네이버 컨벤션에 따르면 될 것 같아요! 저는 타입 변환 후에 공백을 치는 컨벤션을 사용했었는데, 네이버 컨벤션과 헷갈렸던 것 같습니다~!

2023-09-05 04:53 UTC, Byeongju-Kong approved these changes
고생하셨습니다~! 그리고, AuthenticationPrincipal을 Login이라는 이름으로 바꾸라는 리뷰에 대해 OK를 하셨는데, 제가 다른 브랜치에서 임의로 동일한 위치에 AuthenticationPrincipal 어노테이션을 선언해서 API 개발을 진행했는데요! 제가 작업한 브랜치 보다 늦게 머지가 되신다면 인지하시고 Login으로 변경하시면 될 것 같습니다~! 머지 순서가 반대라면 제가 변경하겠습니다~!

2023-09-05 06:04 UTC, kyukong approved these changes
작업 범위가 넓고 고려사항들이 많아 힘드셨을텐데 정말 고생 많으셨습니다!
남은 의논사항들은 따로 얘기해봐요~!

2023-09-05 06:49 UTC, Seongwon97 approved these changes
수고하셨습니다!!
몇가지 코멘트를 남겼는데 확인 부탁드립니다😁

2023-09-05 06:49 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/usecase/UserQueryService.java
> +
이전 PR에서 늦게 남긴 코멘트이긴한데 user와 관련된 port와 usecase를 감싸면 좋을 것 같아요..!!

```
gohigher
   ├ application
   └ user
       ├ port
       └ usecase
```

지원서에 대한 작업도 위와 같은 형태로 되어있고, 기능별로 관리를 하려면 도메인별로 패키지를 분리하는 것이 좋을 것 같아요!!

2023-09-05 06:49 UTC, Seongwon97 commented on core-domain/src/main/java/gohigher/user/AuthErrorCode.java
> +@Getter
오늘 회의때 annotation의 순서 관련해서도 한번 이야기를 나누어보면 좋을 것 같네요!!

2023-09-05 06:49 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		@RequestParam("userId") Long userId, @RequestParam("role") String role) {
사용자로부터 role 정보를 받는 이유가 있을까요??
요청할때 데이터를 받은 후, 로직 안에서 사용하지 않고 응답할 때 그대로 반환하는 것 같네요

2023-09-05 06:49 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +			GohigherResponse.success(new TokenResponse(accessToken, role)));
저도 응답 값을 설정하는 부분이라 api부분에 위치하는 것이 좋다고 생각합니다.

2023-09-05 06:49 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/auth/support/LoginArgumentResolver.java
> +	}
`Login` 어노테이션은 병주님이 간편 등록 PR에서 임시로 만든 `AuthenticationPrincipal`과 같은 역할을 하는 어노테이션일까요??

2023-09-05 07:29 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/support/LoginArgumentResolver.java
> +	}
네네!! 토큰에서 userId를 뺴오는 어노테이션입니다!

2023-09-05 07:32 UTC, shindong96 commented on core-application/src/main/java/gohigher/usecase/UserQueryService.java
> +
반영햇습니다!!ㅎㅎ

2023-09-05 07:34 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		@RequestParam("userId") Long userId, @RequestParam("role") String role) {
role이라는 정보를 Client에게 전달해서 분기처리를 하기 위함입니다!! 해당 api의 발생 시점이 리다이렉션이 일어난 경우라서 client에서 ㅔRequestParam을 추출해서 사용하지 못할거 같아요ㅜㅜ

2023-09-05 07:42 UTC, shindong96 commented on core-domain/src/main/java/gohigher/user/AuthErrorCode.java
> +@Getter
네! 저는 롬복 사용하지 않고 구현할 때 기준으로 진행하긴 했습니다!

2023-09-05 15:59 UTC, shindong96 commented
안녕...내 작고 소중한 브랜치...ㅜ

2023-09-05 15:59 UTC, closed without merging