[FEATURE] 엑세스 토큰에서 식별자를 추출하는 기능 구현
team-go-higher/backend pull request #46
Opened 2023-09-05 16:42 UTC by shindong96

## 작업 내용
- ArgumentResolver를 통해 엑세스 토큰에서 식별자를 추출한다.
- 현재 인증, 인가는 `security 모듈`에서 시행한다.
- 토큰의 발급, 토큰에서 식별자를 추출하는 부분은 `in-adapter-api 모듈`에서 시행한다.

## 논의 사항
- JwtProvider가 `in-adapter-api 모듈`로 가는 바람에 해당 모듈에도 spring-test 의존성이 생겼습니다.

resolve #28

2023-09-06 07:14 UTC, kyukong approved these changes
정말 고생 많으셨습니다!
JWT 관련해서 기능을 처리하는 객체들은 `in` 모듈에, filter 는 `security` 에 있다고 생각하면 될까요??

2023-09-06 07:14 UTC, kyukong commented on core-application/src/main/java/gohigher/user/port/in/UserCommandPort.java
> +package gohigher.user.port.in;
👍

2023-09-06 07:14 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/auth/AuthorizationExtractor.java
> +package gohigher.auth;
기술보다 역할로 나누니 의미가 명확해져 좋네요!

2023-09-06 11:09 UTC, Seongwon97 approved these changes
수고하셨습니다!!
지난 작업 PR과 커밋이 분리되니 리뷰하기가 편해서 너무 좋았던 것 같습니다👍

2023-09-06 11:09 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/user/port/in/UserCommandPort.java
> +package gohigher.user.port.in;
패키지 분리 좋습니다!

2023-09-06 11:09 UTC, Seongwon97 commented on in-adapter-api/src/test/java/gohigher/auth/JwtProviderTest.java
> +	private static final String SECRET = "secretKey".repeat(6);
유빈님이 추천해주신 방법을 사용하셨군요👍

2023-09-06 11:52 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/JwtProviderTest.java
> +	private static final String SECRET = "secretKey".repeat(6);
넵!!맞습니다ㅎㅎ

2023-09-06 12:10 UTC, kyukong commented on in-adapter-api/src/test/java/gohigher/auth/JwtProviderTest.java
> +	private static final String SECRET = "secretKey".repeat(6);
테스트 코드 전반적으로 미리 정해둔 컨벤션 적용이 필요해보입니다!

2023-09-07 04:53 UTC, shindong96 commented
@Seongwon97 @kyukong 다시 리뷰 부탁드려요!!

2023-09-07 05:17 UTC, Seongwon97 requested changes
몇가지 코멘트를 남겼습니다!! 확인부탁드립니다!!

2023-09-07 05:17 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		Date today = new Date();
`Date`타입은 문제가 많아 Java8이후로 `LocalDate`타입이 나오며 Deprecated되고 있습니다..!
Date보다는 LocalDate의 사용을 추천드립니다!!

![image](https://github.com/team-go-higher/backend/assets/57744251/bc04c680-595e-46a7-8533-03bba715d2e2)

2023-09-07 05:17 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +public class TokenController {
아래의 코드와 같이 swagger 설정을 적용해주면 좋을 것 같아요!!

```java
@Tag(name = "지원서")
public interface ApplicationCommandControllerDocs {

	@Operation(summary = "지원서 간편등록")
	@ApiResponses(
		value = {@ApiResponse(responseCode = "200", description = "간편 지원서 등록 성공"),
			@ApiResponse(responseCode = "400", description = "회사명 혹은 직무가 입력되지 않음")
		}
	)
	ResponseEntity<GohigherResponse<Void>> registerApplication(@Parameter(hidden = true) Long userId,
		@RequestBody SimpleApplicationRequest command);
}
```

```java
@RestController
@RequiredArgsConstructor
public class ApplicationCommandController implements ApplicationCommandControllerDocs {

	private final ApplicationCommandPort applicationCommandPort;

	@PostMapping("/v1/application/simple")
	public ResponseEntity<GohigherResponse<Void>> registerApplication(@Login Long userId,
		@RequestBody @Valid SimpleApplicationRequest command) {
		applicationCommandPort.applySimply(userId, command);
		return ResponseEntity.ok(GohigherResponse.success(null));
	}
}

```

2023-09-07 05:17 UTC, Seongwon97 commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +	// }
사용하지 않는 코드는 삭제가 필요할 것 같습니다.

2023-09-07 05:17 UTC, Seongwon97 commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +				ResponseCookie cookie = refreshTokenCookieProvider.create(value);
계층을 나누니 확실히 주석의 필요성이..애매해진것 같긴 하네요ㅠ

2023-09-07 05:17 UTC, Seongwon97 commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +		class ExpireLength {
nested class명은 이렇게 가는걸까요?? 저는 더 상세하게 표현하고 있긴 했습니다..!
```java
class ApplicationRepositoryTest {

	@DisplayName("findByUserIdAndMonth 메소드는")
	@Nested
	class Describe_findByUserIdAndMonth {

		@DisplayName("여러 유저의 공고가 존재하여도")
		@Nested
		class Context_with_many_user_applications {

			@DisplayName("특정 유저의 데이터만 반환한다.")
			@Test
			void it_returns_only_data_for_a_specific_user() {
```

2023-09-07 05:26 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		Date today = new Date();
JWT에서는 expiration을 Date 타입으로 받더라구요.
사실 expiration떄문에 사용하는 것인데 결국 LocalDateTime.ofInstance()를 해서 넣는다면 크게 의미가 없을 거 같아요
어떻게 생각하시나요?

2023-09-07 05:27 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +public class TokenController {
이 부분을 잊었네요!! 반영하겠습니다!

2023-09-07 05:30 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		Date today = new Date();
wow..`Date`타입이 예전 코드에서 사용하는 곳들이 많아서 아직까지 남아있다던디..JWT도 그 중 하나였군요..?

그렇다면 어쩔 수 없는 것 같습니다ㅠ

2023-09-07 05:44 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +	// }
리뷰하시는 틈에 지웠습니다 🤣

2023-09-07 05:54 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/TokenControllerDocs.java
> +	ResponseEntity<GohigherResponse<TokenResponse>> authorize(HttpServletResponse response,
@Byeongju-Kong 혹시 저기 response도 hidden 시켜야하나요?

2023-09-07 05:55 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +		class ExpireLength {
DCI를 다 남기는군요! 저는 이런 방식도 좋아요!!

2023-09-07 05:55 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +		class ExpireLength {
메소드 x 메서드 o ㅋㅋㅋㅋㅋㅋㅋ

2023-09-07 13:21 UTC, kyukong requested changes
간단한 리뷰 몇개 남겨봤습니다...!! 수고하셨어요! 👍

2023-09-07 13:21 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/auth/support/TokenType.java
> +	REFRESH
```suggestion
	ACCESS,
	REFRESH,
	;
```
별건 아니지만.. 토큰 타입이 추가될일은 없지만... 어떠신가요...

2023-09-07 13:21 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		response.addHeader(SET_COOKIE, responseCookie.toString());
```suggestion
		response.addHeader(HttpHeaders.SET_COOKIE, responseCookie.toString());
```
SET_COOKIE 를 static 으로 import 하니 처음 봤을때는 어디에서 가져온 값인지 모르겠더라구요. 이렇게 선언하는건 어떨까요?

2023-09-07 13:21 UTC, kyukong commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +			@DisplayName("엑세스 토큰이 정상적으로 만든다")
```suggestion
			@DisplayName("엑세스 토큰이 정상적으로 만든다.")
```
온점을 붙이는게 좋을까요, 없애는게  좋을까요? 저는 없는 편을 선호하지만 전에 예시에 있던 사진에는 있어서 붙였었습니다!

2023-09-07 13:21 UTC, kyukong commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +
```suggestion
```

2023-09-07 13:21 UTC, kyukong commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +					.getBody();
```suggestion
				Claims claims = extractClaims(accessToken);
```
테스트 가독성을 위해서 메서드 분리를 하는건 어떨까요?

2023-09-07 13:21 UTC, kyukong commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +			Date now = new Date();
```suggestion

			private final Long userId = 1L;
			private final Date now = new Date();
```
아래 테스트에는 접근제어자와 final 이 포함되어 있는데 다른 이유가 있을까요??

2023-09-07 13:21 UTC, kyukong commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +@DisplayName("CookieProvider 클래스의")
```suggestion
@DisplayName("RefreshTokenCookieProvider 클래스의")
```

2023-09-07 13:21 UTC, kyukong commented on security/src/main/resources/application-auth.yml
> +    redirect_uri: 'http://localhost:8080'
redirect uri 가 변경된다면 구글, 카카오 개발자 페이지에 수정이 필요할듯합니다!

2023-09-07 13:38 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/auth/TokenControllerDocs.java
> +	ResponseEntity<GohigherResponse<TokenResponse>> authorize(HttpServletResponse response,
프로그램 실행하고 `localhost:8080/api-docs` 에 접속해서 api명세 뜨는걸 확인해보면 알 수 있을것 같아요!!

2023-09-07 13:41 UTC, Seongwon97 commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +		class ExpireLength {
오...제 PR에서도 변경해야겠군요

2023-09-07 13:42 UTC, Seongwon97 approved these changes
변경 내용 확인했습니다!!
Approve하겠습니다!
수고하셨습니다..!

2023-09-07 14:27 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/support/TokenType.java
> +	REFRESH
좋아요!!

2023-09-07 14:28 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/auth/TokenController.java
> +		response.addHeader(SET_COOKIE, responseCookie.toString());
제가 익숙해서 눈치를 못챘네요 !! 좋습니다 :)

2023-09-07 14:32 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +
😱

2023-09-07 14:33 UTC, shindong96 commented on security/src/main/resources/application-auth.yml
> +    redirect_uri: 'http://localhost:8080'
이 부분은 successhandler에서 client에게 리다이렉트 시키는 것인데 연관이 되나요??

2023-09-07 14:39 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +@DisplayName("CookieProvider 클래스의")
😱

2023-09-07 14:39 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +			Date now = new Date();
아니요! 클래스니까 다 붙이는 걸로 통일했습니다!

2023-09-07 14:40 UTC, shindong96 commented on in-adapter-api/src/test/java/gohigher/auth/support/JwtProviderTest.java
> +					.getBody();
좋아요!

2023-09-07 15:16 UTC, kyukong commented on security/src/main/resources/application-auth.yml
> +    redirect_uri: 'http://localhost:8080'
오잉.. 헷갈렸네요 ㅋㅋ 무관할거같습니다!!!

2023-09-07 15:20 UTC, kyukong approved these changes
반영내용 확인했습니다!
테스트 관련 규칙은 다음에 다시 이야기 나눠봐요!

2023-09-08 00:19 UTC, Byeongju-Kong approved these changes
아스피! 이전에 리뷰들을 다 반영하시고 다시 작업한 것들이라서 크게 리뷰 남길게 없네요! 고생하셨습니다~!

2023-09-08 00:19 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/auth/TokenControllerDocs.java
> +	ResponseEntity<GohigherResponse<TokenResponse>> authorize(HttpServletResponse response,
resposne도 hidden 시키는게 좋아보입니다~!

2023-09-08 00:19 UTC, Byeongju-Kong commented on in-adapter-api/src/test/java/gohigher/auth/support/RefreshTokenCookieProviderTest.java
> +		class ExpireLength {
![스크린샷 2023-09-08 오전 9 18 29](https://github.com/team-go-higher/backend/assets/68771917/22e54006-df4a-4a25-bc36-7f3e8491c95a)
ㅋㅋㅋㅋㅋㅋㅋ

2023-09-08 05:14 UTC, merged

2023-09-08 05:14 UTC, shindong96 commented
로그인 성공!!