[TEST] Spring Security Test
team-go-higher/backend pull request #47
Opened 2023-09-06 06:51 UTC by kyukong

## 작업 내용
- Spring Security 관련 테스트 작성

resolve #22

2023-09-06 06:58 UTC, kyukong commented on bootstrap/src/main/java/gohigher/encryption/config/YamlEncryptionConfig.java
> +	}
- 기존 방식 : System.getProperty()
- 변경 방식 : yml 설정

기존 방식은 JVM 상의 환경변수를 설정하는 방법이고, 변경 방식은 스프링 프레임워크에서 사용하는 설정값입니다. 변경 방식이 값을 설정하기에 더 간단하여 변경하였습니다.

2023-09-06 06:58 UTC, kyukong commented on out-adapter-persistence-jpa/src/test/resources/application.yml
> +      - application-persistence-local.yml
`out` 모듈에서 `@DataJpaTest` 만을 이용하여 테스트하기 위해 yml 파일을 읽어오도록 추가하였습니다.

2023-09-06 06:58 UTC, kyukong commented on out-adapter-persistence-jpa/src/test/java/gohigher/GoHigherApplicationTest.java
> +}
`out` 모듈의 `@DataJpaTest` 에서 Spring Context 를 필수로 요구하여 테스트용 객체를 생성하였습니다.

2023-09-06 07:04 UTC, kyukong reviewed
`bootstrap` 에 있는 security 테스트를 실행하려면 환경변수 설정이 필요합니다.
매번 테스트마다 설정하기 번거로워 gradle 의 기본 옵션을 설정하여, 방법 공유합니다.
가린값은 암호화 키 값입니다.

<img width="1031" alt="image" src="https://github.com/team-go-higher/backend/assets/92148749/df3b4b32-dc08-40c3-966c-25238ec96787">

2023-09-06 11:23 UTC, Seongwon97 requested changes
계층형 테스트코드가 아주 멋지네요!!
리뷰 확인부탁드립니당👍

2023-09-06 11:23 UTC, Seongwon97 commented on bootstrap/src/test/java/gohigher/security/SpringSecurityTest.java
> +@DisplayName("Spring Security 의")
아래의 코드와 같이 DisplayName을 상단으로 올리는건 어떨까요?
```java
@DisplayName("registration 생성은")
@Nested
```

2023-09-06 11:23 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +		}
nested로 `~~할 때`라는 클래스의 displayName에서 주는 의미가 데이터가 주어진 것을 의미하는데 given의 부분을 상위로 올리는 것은 어떨까요?

```suggestion
		@DisplayName("해당 이메일로 가입한 사용자가 있을 때")
		@Nested
		class exist {
			// given
			String email = "test@gmail.com";
			User user = new User(email, Role.USER, Provider.GOOGLE);
				given(userPersistenceQueryPort.findByEmail(email)).willReturn(Optional.of(user));
			@DisplayName("저장되어 있는 정보를 반환해야 한다.")
			@Test
			void success() {
				// when
				User savedUser = userCommandService.login(email, Provider.GOOGLE);

				// then
				assertThat(savedUser).isEqualTo(user);
			}
		}
```

2023-09-06 11:23 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +				// then
막상 계층형으로 테스트 코드를 하다보니 given,when,then이 불필요해보이네요ㅠㅠ

2023-09-06 11:23 UTC, Seongwon97 commented on core-domain/build.gradle
> +    testImplementation 'org.springframework.boot:spring-boot-starter-test'
domain의 경우 spring의 의존이 아예 안 들어가있고 완전한 POJO기반으로 구현되어있는데 junit이 아닌 spring-boot-starter-test의존성을 넣은 이유가 있을까요...??

junit으로만으로도 충분할 것 같습니다..!

2023-09-06 11:23 UTC, Seongwon97 commented on core-domain/src/test/java/gohigher/user/ProviderTest.java
> +			@ValueSource(strings = {"kakao", "Kakao", "KAKAO"})
spring-boot-starter-test의존성의 추가가 parameterizeTest를 위해 추가한 것일까요??

2023-09-06 11:23 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/GoHigherApplicationTest.java
> +}
너무 좋습니다!!

2023-09-06 11:23 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/user/UserPersistenceCommandAdapterTest.java
> +
앞서 남긴 코멘트대로 저는 상위 클래스가 given의 역할을 한다 생각해서 해당 정의는 상위로 이동해도 될 것 같습니다

다른 분들은 어떠신가요??

2023-09-06 11:23 UTC, Seongwon97 commented on security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
> +	public KakaoOAuth2User(final Map<String, Object> attributes) {
```suggestion
	public KakaoOAuth2User(Map<String, Object> attributes) {
```

2023-09-06 11:52 UTC, kyukong commented on bootstrap/src/test/java/gohigher/security/SpringSecurityTest.java
> +@DisplayName("Spring Security 의")
넵 적용했습니다~!

2023-09-06 11:58 UTC, kyukong commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +		}
저는 하나의 테스트 안에 테스트하고자 하는 내용이 명확히 드러나는 편이 좋다고 생각해요! 테스트하려는 기능 외에 셋팅해둬야 하는 경우가 있다면 `@BeforeEach` 등으로 미리 정의하는 것은 동의하나, when 을 실행시키기 위한 준비 과정을 분리하는건 한눈에 보기 어렵다고 생각합니다.

또한, 객체 생성 외에 메서드 호출이 given 영역에 포함되는 경우도 있는데, 이러한 경우 정의하기 번거로워 진다고 생각합니다.
(ex. find 를 호출하기 위해 save 등의 mocking 과정)

2023-09-06 11:59 UTC, kyukong commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +				// then
아직까진 복잡한 테스트가 없어서 그럴수도 있으니.. 일단 붙여보겠습니다ㅠ

2023-09-06 12:06 UTC, kyukong commented on core-domain/build.gradle
> +    testImplementation 'org.springframework.boot:spring-boot-starter-test'
spring test 의존성과 junit 의존성에서 제공하는 기능들의 명확한 차이를 몰라서 편한대로 해버렸네요ㅜㅜ 반영해뒀습니다!

2023-09-06 12:06 UTC, kyukong commented on core-domain/src/test/java/gohigher/user/ProviderTest.java
> +			@ValueSource(strings = {"kakao", "Kakao", "KAKAO"})
assertj 의존성으로 바꾸었습니다!

2023-09-06 12:10 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +		}
저도 @BeforeEach로 지정하는 것을 생각했습니다..!
저는 개인적으로 계층형으로 클래스를 분리하게 된다면 테스트를 파악하는 범위를 테스트 메서드의 상위 클래스까지 봐야한다 생각합니다.
상위 클래스의 displayName만 보더라도 테스트를 하는 상황(given)을 나타내고 있다 생각합니다. 또한 어제 말한대로 여러 테스트를 할 때, 테스트 메서드뱔로 중복되는 given데이터가 계층형으로 구축하면 예방할 수 있다는 말들을 하였는데 이것은 상위 클래스에서 BeforeEach등을 통해 상위 클래스에서 given을 만들어주는 것으로부터 이점이 있다 생각합니다..!!
만약 계층형으로 나눈 클래스들이 단순히 DisplayName의 중복을 줄이는 역할만 한다면 계층의 depth를 줄이는 것이 좋다 생각합니다

2023-09-06 14:34 UTC, kyukong commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +		}
테스트 계층을 given/when/then 형식으로 구분했기 때문에 발생하는 고민인것 같습니다. 하지만 테스트의 구성이 어떻게 되더라도, '테스트 메서드 내에서 테스트 하고자 하는 것이 명확해야 한다' 라는 생각은 변하지 않습니다ㅠ 이는 값을 설정(given), 실행(when), 결과(then) 가 모두 한 곳에 포함되는 것을 의미합니다. 결국 어떤 값을 이용하여 실행했기 때문에 결과가 나타나는 것이기 때문입니다.

`@BeforeEach` 로 given 영역을 구분짓는 것은 역할이 다르다고 생각합니다. BeforeEach 로 설정하는 값은 보통 해당 범위 내 전역적으로 필요한 과정을 수행합니다. 복잡한 테스트를 작성하다보면 다른 테스트와 엮여, 동일한 과정을 수행해야 할 때 BeforeEach 를 사용합니다. 하지만 given 도 BeforeEach 로 처리할 경우, 이것이 when 에 입력하기 위해(given) 만들어진 값인지, when 을 실행하기 위해 전처리 되어야 하는 기능인지 구분하기 어려울것 같습니다.

2023-09-07 14:48 UTC, shindong96 reviewed
일단 급한 코멘트부터 남깁니다!

2023-09-07 14:48 UTC, shindong96 commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +		}
저는 사실 익숙하지 않아서인지 DCI패턴이 가독성에 그다지 좋은지는 모르겠어요. 저도 가독성을 위해서는 한 테스트 안에 given when then이 모두 포함되어 있어야 한다고 생각합니다. 실제로 우테코 미션에서 given 부분이 중복이 되더라도 그걸 밖으로 빼는 것은 가독성을 해칠 수 있다라는 피드백을 받고 공감했던 기억이 있습니다. 

하지만 성원님 생각과 마찬가지로 DCI 패턴을 사용하면서 코드는 테스트 하나하나에 다 들어있다면 그것 또한 큰 이익을 얻지 못한다고 생각합니다. 그래서 저는 DCI 패턴과 g,w,t 중 택해야한다면 후자가 더 좋은 것 같습니다!

( 물론 DCI 패턴이 뭔가 ci를 만들어서 displayname을 쫙볼때는 훨씬 편할 것 같긴해요)

2023-09-07 16:04 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +		}
흠...저는 메서드 내의 `given/when/then`을 모두 적는 것에 대해 익숙해져 있기에 DCI 패턴에서 given을 외부로 빼는 것이 어색해보이는게 아닐까?생각합니다.

저는 개인적으로 DCI에서 Context부분을 Given으로 사용하지 않고 단순히 DisplayName용으로만 사용하는 것은 매번 테스트를 작성할 때마다 depth를 늘리며 inner class를 추가로 만드는 비용의 낭비라 생각합니다. 
가독성 측면에서도 하나의 TC를 살펴볼때 class depth를 2단계를 타고 들어와야하고 상황과 결과를 살펴볼 때 분리된 DisplayName을 봐야하여 가독성이 떨어진다 생각하고요..!

만약 DCI패턴이 어색하여 적용에 거부감이 드신다면 아래와 같이 method 단위로만 inner class를 사용하고 그 외의 상황과 결과에 대한 것은 하나의 메서드로 표현하는 것이 좋지 않을까 합니다.

```java
class ApplicationRepositoryTest {

	@DisplayName("findByUserIdAndMonth 메서드는")
	@Nested
	class Method_findByUserIdAndMonth {

		@DisplayName("여러 유저의 공고가 존재하여도 특정 유저의 데이터만 반환한다.")
		@Test
		void returns_only_data_for_a_specific_user() {
```

2023-09-07 16:05 UTC, Seongwon97 approved these changes
빠른 진행을 위해 Approve하겠습니다..!

2023-09-08 12:19 UTC, Byeongju-Kong approved these changes
고생하셨습니다! DCI 관련해서 이야기를 나누신 곳에 저의 의견도 남겨두었습니다!
이 부분은 조금 더 깊게 이야기를 나눌 필요가 있는 것 같네요!

2023-09-08 12:19 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +	}
해당 객체를 BeforeEach로 초기화하신 이유가 없다면 필드로 초기화해도 될 것 같습니다~!

2023-09-08 12:19 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +		}
저도 DisplayName만을 위해서 사용하는 거면 DCI가 과한 것 같습니다~!
개인적으로, DCI가 맘에 들었던 이유는 DisplayName이 아닌, `중복되는 given 절을 줄일 수 있었기 때문`입니다!

class depth를 타고 들어오거나, DisplayName 들을 보면서, 충분히 given 절을 파악할 수 있다고 생각합니다. given 절이 자신을 감싸고 있는 클래스에 정의되어 있지, 해당 테스트 파일 밖에 존재하는 것도 아니니까요! 또한, given 절이 10줄 이상과 같이 길어질 경우에는 given 절을 파악하기가 더 어렵다고 느꼈습니다!

2023-09-08 12:19 UTC, Byeongju-Kong commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +				// then
`String email = "test@gmail.com";`
`Provider provider = Provider.GOOGLE;`
위와 같은 값들은 클래스의 상수로 지정해도 되지 않을까요~?

2023-09-08 12:19 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/test/java/gohigher/user/UserPersistenceCommandAdapterTest.java
> +
저도 동의합니다! insert class가 단순히 DisplayName 만을 위해 존재하는 것 같습니다!

2023-09-10 12:22 UTC, kyukong commented on core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
> +	}
userPersistenceQueryPort, userPersistenceCommandPort 는 `@Mock` 으로 가져와 userCommandService 를 필드로 가져온다면 Mock 객체들은 모킹되기 전이라 NPE 가 발생합니다! 혹시 다른 방식이 있다면 피드백 부탁드립니다!

2023-09-10 12:23 UTC, merged