[FEATURE] 공고, 지원 테이블 설계 및 엔티티 구현
team-go-higher/backend pull request #5
Opened 2023-08-21 05:29 UTC by Seongwon97

## ⭐️ 작업 내용
현재 아래의 테이블 구조로 엔티티 구현을 완료 하였습니다. 

<img width="779" alt="image" src="https://github.com/team-go-higher/backend/assets/57744251/76d95f42-c6d6-4510-8d86-f49c7f6c9489">

## 🧐 논의하면 좋을 내용
- 백엔드 회의를 하며 테이블간 객체 참조가 아닌 id 참조로 진행하자했는데 조회, 생성 로직 등 공고와 지원서 관련 모든 로직들이 `recruitment`, `recruitment_detail` 테이블과 함께 동작할 것으로 생각되어 객체 참조로 작성했습니다. id참조로 진행하는 것이 좋을 것 같다면 수정하겠습니다.
- db관련한 연결 정보는 현재 서브모듈이 구축되어있지 않고 로컬 db를 연결한 상태라 yml파일 자체를 업로드하였습니다. 추후 서브모듈과 같이 암호화 데이터를 관리하는 체계가 만들어지면 그때 이동시키면 될 것 같습니다.
- Flyway 또한 별도의 이슈를 만들어서 추가하면 좋을 것 같습니다.

2023-08-21 05:30 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private boolean isDeleted;
필드에는 명시적으로 모든 컬럼에 `@Column`을 넣어 매핑을 시킬지 여부와 각각 필드별 공백 라인을 어떻게 통일시킬지도 이야기해보면 좋을 것 같습니다.

2023-08-21 08:26 UTC, Byeongju-Kong approved these changes
성원님 고생하셨습니다! 몇가지 리뷰 남겨두었어요! 해당 브랜치 머지되면 domain <-> jpaEntity 작업도 하시면 좋을 것 같습니다!!

2023-08-21 08:26 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/build.gradle
> +    implementation 'org.springframework:spring-context'
implementation 후에 ()로 할건지 '' 로 할건지 통일하면 좋을 것 같아요~!

2023-08-21 08:26 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private boolean isDeleted;
저는 굳이 `@Column` 어노테이션 사용안해도 좋을 것 같아요! 많아지면 코드 라인이 늘어나서 보기가 힘들 것 같습니다~!

2023-08-21 08:26 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentType.java
> +}
해당 enum은 도메인 쪽에 정의하는게 어떤거 하는 생각이 드네요! 영속성 out adapter에서 정의해서 이점이 크게 없을 거라고 생각해요! 만약 도메인에서 `RecruitmentType`이 필요하다면 도메인에서 out-adapter를 의존할 수는 없기 때문에, 도메인에 또 정의를 해야할 거라고 생각합니다. 반대로 domain에 정의해두고 out-adapter에서 의존하는건 문제가 되지 않겠죠~?

2023-08-21 08:26 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentProcessJpaEntity.java
> +	private LocalDateTime schedule;
마감기한 컬럼인 것으로 보이는데요! deadLine이라는 표현을 어떨까요? 도메인에 정의되어있는 schedule 필드도 deadLined으로요! 다같이 이야기하면서 한번 맞추면 좋을 것 같네요~!

2023-08-22 01:44 UTC, kyukong requested changes
수고하셨어요!
만들어주신 ERD 도 docs 패키지에 추가하는건 어떨까요?

2023-08-22 01:44 UTC, kyukong commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private String duty;
duty 컬럼은 어떤 데이터를 저장하는 값인가요??

2023-08-22 01:57 UTC, Seongwon97 commented on out-adapter-persistence-jpa/build.gradle
> +    implementation 'org.springframework:spring-context'
저는 개인적으로 maven repository에서도 기본적으로 제공하는 `implementation '~~'`으로 통일하는 것이 좋을 것 같습니다.

![image](https://github.com/team-go-higher/backend/assets/57744251/22c95322-03a7-4a51-a3d2-c94d2b13d99c)

2023-08-22 01:59 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentType.java
> +}
`RecruitmentType`속성을 현재 domain에서는 사용하지 않고 Entity에서 값을 저장할 때만 사용하여 out-adapter에 위치시켰는데, 추후 개발을 생각하면 domain에 위치시키는게 좋을 것 같네요!!

위치 변경하겠습니다!!

2023-08-22 01:59 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private String duty;
duty는 직무 데이터 입니다!!

2023-08-22 02:00 UTC, kyukong commented on out-adapter-persistence-jpa/build.gradle
> +    implementation 'org.springframework:spring-context'
저도 성원님 의견에 동의합니다!

2023-08-22 02:00 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private String duty;
@kyukong 혹시 ERD를 docs 패키지에 추가한다는 것은 docs 패키지 안에 ERD 이미지를 저장하는 것일까요??

2023-08-22 02:08 UTC, kyukong commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private String duty;
넵넵 저는 이전 개인 플젝에서 문서를 그렇게 관리했는데, 다른 방법이 있다면 다르게 관리하셔도 괜찮습니다!

2023-08-22 02:13 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentProcessJpaEntity.java
> +	private LocalDateTime schedule;
과정의 경우 `서류 지원`과 `과제`를 제외하고는 마감기한보다는 일정이라는 용어를 사용하게 되어 schedule을 사용하게 되었습니다! 
다른 분들의 의견도 들어보고 맞추면 좋을 것 같네요👍

2023-08-22 02:15 UTC, kyukong commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentProcessJpaEntity.java
> +	private LocalDateTime schedule;
과정 진행중에 마감기한의 의미를 나타내는 경우도 있겠지만, 아닌 경우도 있을것같아 모든 의미를 포함할 수 있는 schedule 그대로 가는것도 좋아보입니다!!

2023-08-22 02:21 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private String duty;
docs 패키지 내에 로 관리하는 것도 좋아보이지만, 테이블에 변동이 있을 때마다 변동을 주는 사람이 ERD 이미지를 최신의 이미지로 변경을 할 수 있을지가 걱정이네요..
만약 팀 내에서 테이블 변동을 줄 때마다 ERD도 업데이트 한다면 저는 찬성입니다.

2023-08-22 02:28 UTC, kyukong commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private String duty;
그러면 프로젝트 내에서 관리할지, 다른 방법(노션 등)으로 관리할지는 팀원들끼리 의논해보고 진행합시다! 일단 넘어가겠습니다~~

2023-08-22 02:29 UTC, kyukong approved these changes
바로 approve 하겠습니다~ 문서 관리 관해서는 나중에 더 이야기 해봐요~!!

2023-08-22 02:45 UTC, shindong96 reviewed
성원님 수고하셨습니다! :)
같이 얘기 나눠보면 좋을 것 같은 부분 코멘트 남겼습니다ㅎㅎ
도메인이랑 엔티티가 다르다보니 이해하는데 쬐끔 빡세네요...ㄷㄷ

2023-08-22 02:45 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	private boolean isDeleted;
저도 `@Column`은 꼭 필요하지 않다고 생각됩니다!

2023-08-22 02:45 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	@Column(updatable = false)
혹시 `updatable = false`를 해두신 이유가 있을까요?

2023-08-22 02:45 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentProcessJpaEntity.java
> +	private RecruitmentJpaEntity recruitment;
이 부분에 대해 이야기할게 좀 있을 것 같아요!
`RecruitmentProcess`가 `ApplicationProcess`가 되야 할지도 모른다는 생각이 드는데요. 만약 저희가 Application을 조회하면서 프로세스를 알고 싶으면 조금 복잡해질 것 같아요ㅜㅜ 

현재 상태로는 아래와 같은 로직을 가질 것 같아요
1. `ApplicationJpa`를 통해 `RecruitmentJpa`를 지연로딩으로 가져온다.
2. `RecruitmentJpa`의 id로 `RecuritmentProcessJpa`들을 조회한다.

제 개인적인 생각으로는 Application을 조회할 때 Process를 같이 응답해줘야하는 상황이 많을 것 같은데 다른 분들은 어떻게 생각하시나요??

2023-08-22 03:45 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentDetailJpaEntity.java
> +	@Column(updatable = false)
앗..실수인것 같습니다..
Public, Private의 정보를 갖는 `RecruitmentType`에 붙인다는 것을 `EmploymentType`에 붙였네요..ㅎㅎ

해당 `@Column(updatable = false)`를 제거하고 `Recruitment`의 `type`필드에 해당 속성을 추가하겠습니다!

2023-08-22 03:49 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentProcessJpaEntity.java
> +	private RecruitmentJpaEntity recruitment;
- 네이밍의 경우, 지원서의 과정과 공고의 과정을 통틀어 표현하게 `Process`라는 네이밍은 어떠신가요??
 - 말씀해주신 `Application을 조회할 때 Process를 같이 응답해줘야하는 상황이 많을 것 같다`는 부분도 동의합니다!! 해당 부분은 양방향 관계를 만들어서 Process 또한 객체 그래프 탐색을 통해 조회할 수 있게 하는 것은 어떻게 생각하시나요?

2023-08-22 07:37 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentProcessJpaEntity.java
> +	private RecruitmentJpaEntity recruitment;
좋은 것 같아요! :)그런데 현재 테이블 상태에서 process가 recruitment와 매핑 되어있는 부분이 조금 어색한 것 같아요
제가 이해가 부족한 상태일수도 있는데 제가 이해한 바로는 아래와 같습니다.

1. `Recruitment`의 상태가 `public`일 때 `Application`과 `1:N`관계가 생깁니다.
2. `Process`의 경우 `Recruitment`당 여러 개가 아니라 `Application`당 여러 개입니다. 
3.  따라서 테이블 매핑이 `Application`과 `Process`간에 생겨야 합니다.

혹시 제가 이해가 잘못된 부분이 있을까요?

2023-08-22 08:30 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/entity/recruitment/RecruitmentProcessJpaEntity.java
> +	private RecruitmentJpaEntity recruitment;
`Application`과 `Process`가 1:N관계인 것도 맞지만, 반대로 관리자가 업로드할 공고도 `RecruitmentDetail`과 `Process`가 1:N의 관계를 갖기도 합니다!!

`Application`과 `RecruitmentDetail`이 모두 Process와 1:N의 관계를 형성하여 만들어진 것이 중간 테이블인 `Recruitment`인 상황입니다!! 

이해가 안 되신다면 추가 질문해주셔도 됩니다!

2023-08-26 05:45 UTC, closed without merging