[FEATURE] 지원서 상세 등록 기능 구현
team-go-higher/backend pull request #56
Opened 2023-09-08 10:33 UTC by Byeongju-Kong

## 작업 내용
- 지원서 상세 등록 기능 구현
- Swagger 응답 예시 기본 포맷 작업

resolve #33

2023-09-08 11:52 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
> +						"""),
위처럼 ExampleObject를 작성하면 아래 사진 처럼 에러 응답 코드들을 나열 해줄 수 있습니다~!

코드들이 길어져서, static 메서드로 추출해서 중복을 줄일 수 있나 했는데, 어노테이션에는 상수밖에 안적히더라고요ㅜ
<img width="569" alt="스크린샷 2023-09-08 오후 7 34 29" src="https://github.com/team-go-higher/backend/assets/68771917/9fd9ebef-1495-4a3a-b099-ea07022afe45">

2023-09-08 12:46 UTC, Byeongju-Kong commented on core-domain/src/main/java/gohigher/common/JobInfo.java
> +	private final String position;
Figma에 있는 지원서의 속성 값들을 보다가, 정의되어 있지 않은 필드가 있어서 정의했습니다~!
@Seongwon97 성원님 조회 API 작업하실 때 참고하셔야 할 것 같습니다~!

2023-09-09 08:42 UTC, Seongwon97 requested changes
안녕하세요 병주님!! 코드 확인했습니다
몇가지 코멘트를 남겼으니 확인부탁드립니다!

2023-09-09 08:42 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/recruitment/entity/RecruitmentJpaEntity.java
> +
하단에 불필요한 공백 라인이 추가됐어요!!

2023-09-09 08:42 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
> +		SpecificApplicationRequest command);
아직 `command`하고 `request`라는 이름들이 혼용되어 사용되는 것 같아요!
클래스 이름을 `~Request`로 정하였으니 파라미터 이름도 request로 변경하는것은 어떨까요?

2023-09-09 08:42 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
> +	@PostMapping("/v1/application/specific")
```suggestion
	@PostMapping("/v1/applications/specific")
```

2023-09-09 08:42 UTC, Seongwon97 commented on core-domain/src/main/java/gohigher/common/JobInfo.java
> +	private final String position;
저는 일단 캘린더 작업 중이라 일부 데이터만을 반환하면 되어서 괜찮을 것 같습니다!
오히려 제가 지금 pr에서 필드를 추가하면 코드 충돌이 많이 발생할 것 같아요!

상세 조회 api는 병주님 pr을 머지한 후에 진행해야겠네요😁

2023-09-09 08:42 UTC, Seongwon97 commented on core-domain/src/main/java/gohigher/application/Application.java
> +			List.of(process), url, process);
볼때마다 끔찍하긴 하네요...builder패턴을 사용하던가 다른 해결 법을 한번 찾아봐야겠네요ㅠㅠ

2023-09-09 08:42 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
> +	private List<SpecificApplicationProcessRequest> processes;
상세 등록에 마감기한(`deadline`)을 제어한 이유가 있을까요?

2023-09-09 08:42 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/SpecificApplicationProcessRequest.java
> +	private LocalDateTime schedule;
- 세부 전형은 전형에 따라 값이 없는 경우도 있어서 @NotNull 제약조건이 없어도 될 것 같습니다!
- schedule같은 경우도 일정은 초반에 공고를 등록할 때 면접일자 등의 일자는 알지 못해서 빈 값을 주어야하기에 @NotNull 제약조건을 없애야 할 것 같아요!

2023-09-09 08:42 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/SimpleApplicationProcessRequest.java
`SpecificApplicationProcessRequest`에 있는 type에 대한 @NotNull 제약조건을 넣어주면 좋을 것 같습니다!

2023-09-10 13:42 UTC, kyukong approved these changes
병주님 수고하셨습니다!

이 PR 에 테스트는 없는데, 다른 PR 에 추가하시려는 걸까요?

저는 테스트를 하면서 잘못 작성한 부분을 찾아내는 경우도 있어서,
보통 하나의 PR 에 테스트까지 포함하는 편이기는 합니다!

2023-09-10 13:42 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
>  	@PostMapping("/v1/application/simple")
ApplicationCommandController 에 API 가 두 개 선언되었으니 `@RequestMapping` 을 사용해도 좋을듯합니다.

2023-09-10 13:42 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
> +			.body(GohigherResponse.success(null));
```suggestion
		return ResponseEntity.created(URI.create("/v1/applications/" + applicationId))
			.body(GohigherResponse.success(null));
```

2023-09-10 13:42 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
> +	)
```suggestion
	})
```
해당 클래스는 길이가 길어질 수밖에 없을듯한데 조금이라도 줄여보는건 어떨까요ㅠㅠ

2023-09-11 01:43 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
> +		SpecificApplicationRequest command);
인지하고 있었는데요! 다른 issue로 진행하려고 했습니다..! 바로 변경하겠습니다~!

2023-09-11 01:46 UTC, Byeongju-Kong commented on core-domain/src/main/java/gohigher/application/Application.java
> +			List.of(process), url, process);
ㅜㅜ

2023-09-11 01:49 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
> +	private List<SpecificApplicationProcessRequest> processes;
첫번째 전형의 전형 일자와 동일하다고 생각해서 제거했습니다~!
마감일이란 서류 마감을 뜻하는 것일텐데요. 간편 등록시에 서류 전형을 등록한다면 서류 전형의 일자가 자연스럽게 마감일이 되겠지요!

2023-09-11 01:52 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/SpecificApplicationProcessRequest.java
> +	private LocalDateTime schedule;
해당 제약 조건들은 제거 했습니다~!

2023-09-11 02:00 UTC, Byeongju-Kong commented
> 병주님 수고하셨습니다!
> 
> 이 PR 에 테스트는 없는데, 다른 PR 에 추가하시려는 걸까요?
> 
> 저는 테스트를 하면서 잘못 작성한 부분을 찾아내는 경우도 있어서, 보통 하나의 PR 에 테스트까지 포함하는 편이기는 합니다!

@kyukong PR을 올렸던 했던 시점에는 E2E 테스트를 할 수 없는 상황이었습니다! E2E 테스트 추가해두겠습니다~!

2023-09-11 02:12 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
> +	)
최대한 닫는 괄호들을 모아서 줄여보았습니다!

2023-09-11 15:44 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
> +	private List<SpecificApplicationProcessRequest> processes;
그렇다면 Application이랑 테이블에서도 deadline필드를 없애거나 백이나 프론트단에서 서류전형이 들어올때 deadline에 값 추가를 요청하는?그런 처리가 필요할 것 같네요!

2023-09-11 15:45 UTC, shindong96 approved these changes
병주님 고생하셨습니다!
메서드 네이밍 관련 코멘트가 있는데 한 번 봐주세요!

2023-09-11 15:45 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
> +			applicationRepository.save(ApplicationJpaEntity.from(userId, application));
재가 알기론 일반적으로 파라미터가 1개일 때가 from으로 알고 있는데요! 혹시 from으로 돌아간 이유가 있을까요???

2023-09-11 15:45 UTC, Seongwon97 approved these changes
이만 Approve하겠습니다!!
deadline에 대한 처리는 Null값을 넣어두기보다는 한번 규칙을 정하는게 좋긴 할거같아요!

2023-09-11 16:02 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
> +			applicationRepository.save(ApplicationJpaEntity.from(userId, application));
#61 이슈 따로 빼서 진행하겠습니다~! 바로 붙혀서 작업 중인 브랜치가 있어서 충돌이 너무 많을 것 같네요!

2023-09-11 16:02 UTC, merged