[FEATURE] 지원서의 현재 진행 중인 전형 변경 API 구현
team-go-higher/backend pull request #59
Opened 2023-09-08 16:14 UTC by Byeongju-Kong

## 작업 내용
- 지원서의 현재 진행 중인 전형 변경 API 구현

resolve #57

2023-09-11 15:07 UTC, Seongwon97 requested changes
수고하셨습니다 병주님
코멘트를 남겼으니 확인 부탁드립니다!!
request 값에 processType은 한번 생각해보면 좋을 것 같습니다!

2023-09-11 15:07 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/CurrentProcessUpdateRequest.java
> +	private String currentProcessType;
여기에는 NotNull 조건을 붙여도 될 것 같아요!

2023-09-11 15:07 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
> +			EmploymentType.from(employmentType), careerRequirement, requiredCapability, preferredQualification, null,
현재 Figma 상세 등록 페이지에 마감기한 칸이 없어서 deadline을 받지 않고 null값을 준 것일까요??

그런거라면 내일 회의때 deadline이 없이 서류기한으로만 관리할지 아님 deadline도 따로 관리할지 이야기를 나눠봐야겠네요!

2023-09-11 15:07 UTC, Seongwon97 commented on core-domain/src/main/java/gohigher/application/Application.java
core 내부 도메인에서도 userId를 갖는 것에 대해 한번 이야기를 나눠보면 좋을 것 같아요!

저는 개인적으로 도메인을 만들 당시 우리 서비스의 요청은 "내" 지원서만을 데이터베이스로부터 읽어오고 저장하고 사용자에게 반환하는 것이라 core 내부에서 userId는 필요 없는 관심사라 생각해서 추가하지 않았습니다!

오히려 userId는 데이터베이스로부터 저장하고 읽을 때, 추가적으로 필요한 관심사라 생각하여 outport로 넘겨줄때 별도로 넘겨주고, out-persistence 모듈에서 userId와 application을 통해 entity를 만드는게 좋지 않을까 생각합니다!

2023-09-11 15:07 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/application/service/ApplicationCommandServiceTest.java
> +					.doesNotThrowAnyException();
오 `assertThatCode`는 처음 보는 메서드네요!!

2023-09-11 15:07 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
> +		validateForbidden(application, userId);
만약 core-domain의 Application에서 userId를 없앤다면 `findByIdAndUserId`와 같이 where 조건을 2개를 넣어서 조회하면 validateForbidden을 없앨 수도 있을 것 같아요!

2023-09-11 15:07 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
> +		applicationPersistenceCommandPort.updateCurrentProcessOrder(applicationId, processOrder);
현재 로직을 살펴보면 아래와 같은 플로우로 흘러가는 것 같아요.
1. 사용자로부터 ProcessType 값을 받는다.
2. 등록된 Process중에서 일치하는 ProcessType중 첫번째 값의 순서를 반환한다.
   - 만약 일치하는 ProcessType이 없다면 Exception
3. 해당 Order로 현재 상태를 업데이트

하지만 우리 서비스는 프로세스 단계별로 N개의 일정이 등록되어있을 수 있기에 현재 진행중인 전형 변경에서 위와 같이 ProcessType을 통해 진행한다면 같은 ProcessType 내에서 2번째 3번째로 위치하는 상태로는 변경할 수가 없을 것 같아요!

이를 위해 사용자로부터 ProcessType이 아닌 process order값을 받고, 해당 order값을 통해 변경하는것은 어떨까요?

2023-09-11 15:07 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
> +		List.of(firstProcess, secondProcess, thirdProcess), "", 1L, firstProcess);
제 PR이 머지되면 Fixture를 사용해보시죠!

2023-09-11 15:07 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
> +@Transactional
@DataJpaTest가 아닌 @SpringBootTest를 추가한 이유는 ApplicationPersistenceCommandAdapter를 등록하기 위함일까요??

2023-09-11 16:17 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
> +@Transactional
네!

2023-09-11 16:18 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
> +		List.of(firstProcess, secondProcess, thirdProcess), "", 1L, firstProcess);
네! 이슈 하나 파서 그렇게 해야할 것 같네요!

2023-09-11 16:18 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
> +		validateForbidden(application, userId);
이 부분 한번 내일 이야기 나눠볼까요? userId 도메인 포함 여부에 대해서요!

2023-09-11 16:19 UTC, Byeongju-Kong commented on core-domain/src/main/java/gohigher/application/Application.java
내일 회의 때 한번 이야기 해보시죠!

2023-09-11 16:19 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/CurrentProcessUpdateRequest.java
> +	private String currentProcessType;
추후 commit에서 반영했습니다!

2023-09-11 16:19 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
> +			EmploymentType.from(employmentType), careerRequirement, requiredCapability, preferredQualification, null,
넵! 내일 이야기 해보시죠!

2023-09-11 16:23 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
> +		applicationPersistenceCommandPort.updateCurrentProcessOrder(applicationId, processOrder);
칸반 변경의 경우에, 사용자가 다음 ProcessType 칸반을 넘겼을 떄 아래와 같은 분기가 나올 것 같아요.
- 동일한 ProcessType의 여러 전형 중 어떤 것으로 현재 전형을 변경시킬지
- 만약 해당 ProcessType이 없다면?

따라서, 칸반에서 특정 ProcessType으로 현재 진행 전형을 변경했을 때, 해당 ProcessType에 대한 전형들을 넘겨주는 API가 한번 있어야 한다고 생각합니다!
그걸 모르고 해당 이슈 작업을 먼저했어요. 따라서, 입력 객체를 아래와 같이 변경했는데 확인 부탁드립니다!

```java
public class CurrentProcessUpdateRequest {

	@NotNull(message = "APPLICATION_004||지원서 id가 입력되지 않았습니다.")
	private Long applicationId;
	@NotNull(message = "APPLICATION_005||지원서의 전형 id가 입력되지 않았습니다.")
	private Long processId;
}
```

2023-09-11 16:24 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/CurrentProcessUpdateRequest.java
> +}
칸반 변경의 경우에, 사용자가 다음 ProcessType 칸반을 넘겼을 떄 아래와 같은 분기가 나올 것 같아요.

동일한 ProcessType의 여러 전형 중 어떤 것으로 현재 전형을 변경시킬지
만약 해당 ProcessType이 없다면?
따라서, 칸반에서 특정 ProcessType으로 현재 진행 전형을 변경했을 때, 해당 ProcessType에 대한 전형들을 넘겨주는 API가 한번 있어야 한다고 생각합니다!
그걸 모르고 해당 이슈 작업을 먼저했어요. 따라서, 입력 객체를 아래와 같이 변경했는데 확인 부탁드립니다!

2023-09-13 06:02 UTC, Seongwon97 approved these changes
PR을 너무 길게 끌고가는 것 같아 일단 Approve하겠습니다!

몇가지 피드백을 남겼으니 확인 부탁드립니다!!
domain-Application의 userId는 다 같이 한번 이야기를 나눠보죠..!

2023-09-13 06:02 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
> +		applicationCommandPort.updateCurrentProcess(userId, request);
`@Valid` 어노테이션이 누락된 것 같습니다!

2023-09-13 06:02 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
> +					""")}))})
다른 인터페이스 어노테이션처럼 줄 바꿈이 좀 있으면 좋을 것 같습니다!

2023-09-13 06:02 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessRepository.java
> +	Optional<ApplicationProcessJpaEntity> findByIdAndApplicationId(Long id, Long applicationId);
```suggestion
	@Query("SELECT ap FROM ApplicationProcessJpaEntity ap 
	WHERE ap.id = :id 
	AND ap.application.id = :applicationId")
	Optional<ApplicationProcessJpaEntity> findByIdAndApplicationId(Long id, Long applicationId);
```
쿼리의 가독성을 위해 줄바꿈을 하는건 어떨까요?

2023-09-13 06:02 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
> +	void updateCurrentProcess(Long userId, CurrentProcessUpdateRequest command);
request에서 command로 돌아온 이유가 있을까요??

2023-09-13 06:02 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/application/service/ApplicationCommandServiceTest.java
> +	Application application = new Application("", "", "", "", "", "", "", "",
이제 TestFixture를 활용해도 될 것 같아요!

2023-09-13 06:02 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/recruitment/entity/RecruitmentJpaEntity.java
> +
공백 라인이 하나 더 추가됐습니다!

2023-09-13 06:02 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationProcessPersistenceQueryAdapterTest.java
> +}
여기에는 공백 라인 추가가 필요할 것 같아요!

2023-09-13 06:02 UTC, Seongwon97 commented on core-domain/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.9.2'
현재 우리가 사용하는 Spring-boot-starter-test는 jupiter버전 5.9.3을 사용중이라 우리가 모듈에 개별로 추가하는 버전이 5.9.2면 버전만 다른 중복된 의존성이 추가되더라고요!

<img width="410" alt="image" src="https://github.com/team-go-higher/backend/assets/57744251/54752a5c-1709-4cfa-80d9-4d03e676f7f0">

그래서 5.9.3으로 버전을 맞추면 더 좋을 것 같습니다!
제가 다른 버전은 다 변경했었는데 위의 `testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'`는 누락이 됐었네요ㅠㅠ

추가로 나중에 비슷한 문제가 발생하지 않게 이슈를 하나 만들어서 spring-boot-starter 등의 의존성 버전도 명시를 해보겠습니다!

2023-09-13 06:02 UTC, Seongwon97 commented on core-domain/src/main/java/gohigher/application/Application.java
@shindong96 @kyukong 다른 분들은 어떻게 생각하시나요?

2023-09-13 07:10 UTC, shindong96 reviewed
병주님 고생하셨습니다!
따로 코멘트는 달지 않았는데 궁금한 점이 있습니다.

현재 로직에서 보면 application의 currentProcess를 변경하는 것이 핵심인 것으로 보입니다. 

```
1. persistence로 부터 ApplicationJpaEntity를 이용해 Application 객체를 가져온다.
2. core-application에서 persistence에 applicationId와 process.order를 이용하여 update 쿼리를 날리게 한다.
```

이런 과정으로 파악했는데 혹시 1번 과정이 지나고 persistence 모듈의 역할이 끝나면 2번 과정이 진행되기 전에 1차 캐시가 종료되는지 궁금합니다! 
만약 core-application의 트랜잭션의 생명주기와 같이 영속성 컨텍스트가 유지 중이라면 변경 감지를 통한 update도 가능하지 않을까요??

2023-09-13 07:10 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/CurrentProcessUpdateRequest.java
> +	@NotNull(message = "APPLICATION_005||지원서의 전형 id가 입력되지 않았습니다.")
개행!! :)

2023-09-13 07:10 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
> +                .findByIdAndApplicationId(request.getProcessId(), applicationId)
Process을 PK로 조회를 하는데 Application의 PK도 함께 조회하는 이유가 있을까요?

2023-09-13 07:10 UTC, shindong96 commented on core-domain/src/main/java/gohigher/application/Application.java
이런 부분은 생각하지 못했었네요...! 제 생각에도 저희 서비스의 경우 사용자가 자신의 Application만을 조작하기 때문에 userId가 도메인에는 없어도 될 거란 생각이 드네요

2023-09-13 07:44 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
> +		validateForbidden(application, userId);
해당 상황의 경우 403의 에러가 필수적이지는 않다고 생각됩니다..!

만약 서비스 로직 내에서 병주님의 구현대로 사용자가 다른 사용자의 지원서를 조회할 수 있는 로직의 형태라면 403에러가 필요하겠지만 로직의 구현 자체를 `findByIdAndUserId` 사용자가 다른 사용자의 지원서를 조회하지 못하도록 구현한다면 403에 대한 에러 처리가 없어도 되지 않을까 합니다!

지금 구현의 경우는 403에러 처리를 위해 domain에 userId 필드를 추가하게 된 상황인데, 개인적인 생각으로는 403을 위해 도메인에 변화를 주는 것 보다는 "404로 지원서 조회 에러"를 반환하는게 더 좋지 않을까 하는 생각입니다!!

2023-09-13 12:59 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
> +		applicationCommandPort.updateCurrentProcess(userId, request);
깜빡했네요! 추가했습니다!

2023-09-13 13:03 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
> +	void updateCurrentProcess(Long userId, CurrentProcessUpdateRequest command);
충돌 해결하다가 이렇게 된 것 같네요! 다 request로 변경했습니다~!

2023-09-13 13:04 UTC, Byeongju-Kong commented on core-domain/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.9.2'
확인하고 충돌 해결하면서 버전 통일시켰습니다~!

2023-09-13 13:17 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
> +                .findByIdAndApplicationId(request.getProcessId(), applicationId)
음 특별한 이유는 없었지만, 좀 더 방어적으로 설계하고 싶었습니다!
processId와 applicationId가 모두 존재하지만 processId를 가진 Process는 applicationId를 가진 Application에 해당하지 않는? 경우를 막으려고 했습니다.
물론, 사용자의 정상적인 흐름이라면 나타나지 않을 것으로 생각됩니다! processId 만을 조건으로 찾도록 변경했습니다~!

2023-09-13 14:14 UTC, merged