[FEATURE] 캘린더 일별 조회 API 구현
team-go-higher/backend pull request #74
Opened 2023-09-14 07:14 UTC by shindong96

## 작업 내용
- 캘린더에서 날짜로 일별 지원전형 조회를 하는 기능을 구현
- 당일 0시 이상 익일 0시 미만으로 조회

## 변경 사항
- 월별 조회 메서드의 이름을 변경하였습니다. 

resolve #67

2023-09-14 08:52 UTC, Seongwon97 approved these changes
동석님 수고 많으셨습니다👍

2023-09-14 08:52 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/CalendarApplicationRequest.java
> +public class CalendarApplicationRequest {
와우...`calendar`였군요..ㅎ

2023-09-14 08:52 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/DateApplicationRequest.java
> +	private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(Pattern.DATE.getFormat());
```suggestion
public class DateApplicationRequest {

	private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(Pattern.DATE.getFormat());
```

2023-09-14 08:52 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
> +		LocalDateTime endOfDate = date.plusDays(1).atStartOfDay();
`.atStartOfDay()` 👍👍

2023-09-14 08:52 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
> +	List<ApplicationJpaEntity> findByUserIdAndDate(Long userId, LocalDateTime startOfDate, LocalDateTime endOfDate);
위의 코드들과 통일성을 맞춰보는건 어떨까요?

```suggestion
		+ "AND p.schedule >= :startOfDate "
		+ "AND p.schedule < :endOfDate")
	List<ApplicationJpaEntity> findByUserIdAndDate(Long userId, LocalDateTime startOfDate, LocalDateTime endOfDate);
```

2023-09-14 08:52 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
> +	}
해당 메서드는 달력 관련 기능에 사용되는 완전하지 않은 도메인을 만드는 메서드가 맞을까요?

2023-09-14 08:52 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +	public ResponseEntity<GohigherResponse<List<DateApplicationResponse>>> findByDate(@Login Long userId,
월별 조회를 `v1/applications/month ~~`, 
일별 조회를 `v1/applications/date ~~`의 형식으로 가보는건 어떨까요??

2023-09-14 08:52 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +	public ResponseEntity<GohigherResponse<List<DateApplicationResponse>>> findByDate(@Login Long userId,
그리고 지금 생각이 든 것인데 제가 만든 월별 조회 api하고 동석님이 만든 api 모두 쿼리파라미터가 아니고 pathVariable로 가는 것도 좋지 않을까?하는 생각도 드네요!

`v1/applications/month/2023-09`, `v1/applications/date/2023-09-14` 처럼요..! (막상 적어보니 이상해보이기도 하네요)

위와 같은 생각이 든 이유는 일별 조회 쿼리의 현재 Api가 `v1/applications/processes/date?date = ~`와 같이 고정된 path의 마지막 keyword와 queryParam의 key가 동일하여 어색하다는 느낌이 들었기 떄문입니다!

2023-09-14 08:52 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/Pattern.java
> +	DATE("yyyy-MM-dd"),
`Pattern`보다는 `DatePattern`이 더 좋을 것 같아요!

2023-09-14 12:13 UTC, kyukong requested changes
전체적으로 코드가 깔끔해서 보기 편했습니다
남긴 리뷰는 별건 없지만 답변이 궁금해서 Request Changes 로 할게요!

2023-09-14 12:13 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +	public ResponseEntity<GohigherResponse<List<DateApplicationResponse>>> findByDate(@Login Long userId,
```suggestion
	}

	@GetMapping("/calendar")
	public ResponseEntity<GohigherResponse<List<DateApplicationResponse>>> findByDate(@Login Long userId,
```

date 가 반복되어 어색하다면 동일 URI 에 대해 파라미터 값의 여부로 분기쳐주면 어떨까요?

2023-09-14 12:13 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
>  		return ResponseEntity.ok(GohigherResponse.success(response));
```suggestion
		@ModelAttribute DateApplicationRequest request) {
		List<DateApplicationResponse> response = applicationQueryPort.findByDate(userId, request);
		return ResponseEntity.ok(GohigherResponse.success(response));
```

저번에 성원님 PR 에도 남겼던 리뷰인데, `@ModelAttribute` 가 아닌 `@RequestParam` 을 사용하신 이유가 있나요?

2023-09-14 12:13 UTC, kyukong commented on core-application/src/test/java/gohigher/application/port/in/DateApplicationRequestTest.java
> +		@ValueSource(strings = {"202-12-24", "20232-12-23", "2023-1-23", "2023-09-232", "20230908"})
꼼꼼한 테스트 아주 좋네요

2023-09-14 12:13 UTC, kyukong commented on core-application/src/main/java/gohigher/application/port/in/Pattern.java
> +	DATE("yyyy-MM-dd"),
오.. enum 으로 관리하니 훨씬 깔끔하고 괜찮네요 배워갑니다 👍👍👍

그리고 성원님 의견처럼 Pattern 은 기본 자바 객체가 이미 있으니 이름을 변경하는 것도 좋아보입니다!

2023-09-14 12:13 UTC, kyukong commented on core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
> +	List<Application> findByUserIdAndDate(long userId, LocalDate date);
```suggestion
	List<Application> findByUserIdAndDate(Long userId, LocalDate date);
```
Request 에서는 Wrapper 로 받아왔는데, 별다른 검증 없이 long 으로 받는다면 NPE 가 발생할 수도 있을것 같습니다.

2023-09-14 12:13 UTC, kyukong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +				processResponse));
```suggestion
	private Stream<DateApplicationResponse> extractDateApplicationResponses(Application application) {
		return application.getProcesses().stream()
			.map(ProcessResponse::from)
			.map(response -> DateApplicationResponse.of(application.getId(), application.getCompanyName(), response));
```
바로 윗 줄의 코드와 같이 DTO 내부로 숨기는건 어떤가요?

2023-09-14 13:06 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/CalendarApplicationRequest.java
> +public class CalendarApplicationRequest {
레전드.. 저도 몰랐습니다...

2023-09-14 13:20 UTC, Byeongju-Kong approved these changes
고생하셨습니다~! 캘린더 스펠링이 진짜 웃프네요...😂 저도 몰랐습니다!
Request Change 할 만큼 중요한 리뷰는 없던 것 같아서 Approve 하겠습니다~!
리뷰 읽어보시고 간단한 것들이니 고려-반영 해보시길 바라요~!

2023-09-14 13:20 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/DateApplicationRequest.java
> +	public DateApplicationRequest(Long userId, String dateStr) {
```suggestion
	public DateApplicationRequest(Long userId, String date) {
```
그냥 date 라고 표현해도 될 것 같습니다~!

2023-09-14 13:20 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/DateApplicationRequest.java
> +			throw new GoHigherException(ApplicationErrorCode.INVALID_DATE_INFO);
날짜 포맷으로 파싱이 안된거니까 INVALID_DATE_FORMAT은 어떠신지요!

2023-09-14 13:20 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/ProcessResponse.java
> +	}
Pattern.DATE에 process.getSchdule을 넘겨서 String을 받는건 어떨까요?

2023-09-14 13:20 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
>  			request.getYear(), request.getMonth());
```suggestion
		List<Application> applications = applicationPersistenceQueryPort.findByUserIdAndYearAndMonth(request.getUserId(),
			request.getYear(), request.getMonth());
```

매개변수에 Year과 Month가 있어서 위처럼 변경하는건 어떨까요? 혹은 findByIdAndDate? 정도요!

2023-09-14 13:20 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
>  				application.getCompanyName(), process.getType().name(), process.getSchedule()));
CalemdarApplicationResponse의 매개변수를 Application와 Process 타입으로 지정하면 어떨까요?
그럼 Service 객체의 코드는 좀더 깔끔해질 것 같네요!
Response 할당 로직이 엄청 복잡하지 않고, 테스트 코드로도 충분히 검증할 수 있다고 생각해서 제안드려봅니다~!

2023-09-14 13:20 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +		return application.getProcesses().stream()
```suggestion
		return application.getProcesses()
		.stream()
```

2023-09-14 13:20 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +	public ResponseEntity<GohigherResponse<List<DateApplicationResponse>>> findByDate(@Login Long userId,
저는 현재의 쿼리파라미터 방식이 좋은 것 같습니다~!

2023-09-14 13:20 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/DateApplicationRequest.java
> +			throw new GoHigherException(ApplicationErrorCode.INVALID_DATE_INFO);
여기서 처리한 에러는 혹시 Swagger에 문서화 하셨을까요~?

2023-09-14 13:20 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
> +		return convertToDomain(applicationJpaEntities);
이 부분은 convertToDomain 메서드를 빼지 않고 쭉 적어버려도 깔끔하게 읽힐 것 같네요!

2023-09-14 13:57 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/CalendarApplicationRequest.java
> +public class CalendarApplicationRequest {
심지어 인텔리J도 모른다는...ㄷㄷ 초록줄 조차 없는ㅋㅋ

2023-09-14 14:00 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
> +	}
넵 맞습니다!!만약 캐리어를 쓰게 되면 없어질거 같아요!

2023-09-14 14:01 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +	public ResponseEntity<GohigherResponse<List<DateApplicationResponse>>> findByDate(@Login Long userId,
파라미터 여부로 분기처리가 안되더라구요ㅜㅜ저도 파라미터 방식을 선호하는게 파라미터가 필터링(범위 등)의 관점이고 pathVariable은 어느 특정 리소스로 접근한다는 걸 명시하는 것으로 알고있습니다!

2023-09-14 14:03 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/Pattern.java
> +	DATE("yyyy-MM-dd"),
만약 월별 조회도 해당 방식으로 리팩토링한다면 여기 추가하면 될 거 같아요!

2023-09-14 14:04 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
>  		return ResponseEntity.ok(GohigherResponse.success(response));
큰 이유는 없지만 파라미터의 갯수가 3개 이하이기에 가독성 측면에서 파라미터가 낫다고 판단했습니다!

2023-09-14 14:07 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
> +	List<Application> findByUserIdAndDate(long userId, LocalDate date);
맞는 말씀이십니다! 반영하겠습니다 :)

2023-09-14 14:14 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +				processResponse));
생성자와 팩토리 메서드의 차이이기에 큰 변화를 느끼기는 어려운거 같아요!
그래서 말씀해주신 `DateApplicationResponse.of(application,process)`의 형태로 변경하고 내부에서 필요한 필드들을 get하는 방식으로 변경하였습니다!

2023-09-14 14:16 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/DateApplicationRequest.java
> +	public DateApplicationRequest(Long userId, String dateStr) {
엇 메서드 분리로 하기전에 했던 것이....ㅎ반영하겠습니다!

2023-09-14 14:18 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/DateApplicationRequest.java
> +			throw new GoHigherException(ApplicationErrorCode.INVALID_DATE_INFO);
에러 문서화는 하였습니다! 날짜 정보가 제대로 안 들어온 것인지 형식이 잘못된건지 확인을 할 수 가 없어서 해당 방식을 유지해도 될거 같은데 어떻게 생각하시나요?

2023-09-14 14:19 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/ProcessResponse.java
> +	}
와 제가 하나 놓칠뻔한 점이 시간을 안반환해주었네요...ㄷㄷ

2023-09-14 14:37 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
> +		return convertToDomain(applicationJpaEntities);
중복 코드라 분리하였습니다!

2023-09-14 14:39 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +	public ResponseEntity<GohigherResponse<List<DateApplicationResponse>>> findByDate(@Login Long userId,
그리고 저도 `v1/applications/processes/date?date = ~` 이 어색해서 이런 방식을 사용하게 되었습니다.
`v1/applications/processes/date?value = ~` 도 조금 어색하고...

2023-09-15 02:37 UTC, kyukong approved these changes
반영해주신 것들 모두 확인했습니다~
다들 API 개발 속도가 점점 빨라지는것같아 좋네요 ㅎㅎ
수고하셨습니다!

2023-09-15 03:46 UTC, merged