[FEATURE] 칸반 지원서 목록 조회 API 생성
team-go-higher/backend pull request #75
Opened 2023-09-14 11:27 UTC by kyukong

## 작업 내용
- 칸반에 띄워질 지원서 목록들을 조회하는 API 를 구현했습니다.

resolve #49

2023-09-14 13:39 UTC, Byeongju-Kong requested changes
유빈님! 고생하셨습니다~ 자잘한 리뷰 몇개와 CurrentProcess와 Projection 관련해서 리뷰 남겨두었습니다!
읽어보시면 답변 해주세요!

2023-09-14 13:39 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/KanbanApplicationResponse.java
> +				.toList()
이  부분을 변수로 빼는게 더 깔끔할 것 같은데 어떻게 생각하시나용~?

2023-09-14 13:39 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +	public List<KanbanApplicationResponse> findForKanban(Long userId) {
와 칸반에 영어로 Kanban 인지는 상상도 못했네요. 일본어인줄...?

2023-09-14 13:39 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +			.toList();
```suggestion
		return groupedProcesses.entrySet()
		.stream()
			.map(process -> KanbanApplicationResponse.from(process.getKey().name(), process.getValue()))
			.toList();
```

2023-09-14 13:39 UTC, Byeongju-Kong commented on core-domain/src/main/java/gohigher/application/CurrentProcess.java
> +}
CurrentProcess라는 도메인을 선언하시고 db out-adapte에서는 CurrentProcessDto라는 이름으로 Projection을 사용하셨네요!
객체에 null을 할당하지 않고, DB에서도 필요한 정보만 딱! 가져올 수 있는 좋은 방법 일 수도 있겠습니다!

하지만,,, 저는 개인적으로 이 방식이 조금은 위험할 수도 있다고 생각합니다.

칸반에 띄워줄 데이터는 CurrentProcess의 필드에 해당하는 7개뿐이라, 기존의 도메인을 사용했을 시에 많은 필드들이 null인 상태기 때문에 CurrentProcess를 선언하시고 Projection을 사용하신 것 같아요!

그렇다면, `View에서 노출시켜줘야할 데이터는 7개`이다. 라는 View의 요구사항이 domain와 db out-adapter 까지 들어왔다고 생각합니다. 위의 방식으로 개발을 계속 진행하게 되면 `View에서 노출시켜야 할 데이터에 따라서 Domain을 정의해야하고 db out-port, db out-adapter에 메서드가 계속 생성`해야 하겠죠ㅜ

이렇게 되면 도메인, out-port, out-adatper를 재사용할 수 없고 view에 따라 1개씩 만들어야 하는 상황이 올 것입니다...!
저는 이미 정의된 도메인으로 조회해서 응답하는 방식이 좋은 것 같습니다!

2023-09-14 13:39 UTC, Byeongju-Kong commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
> +	)
와우..!! 쿼리 실력이 대단하시네요! 저는 쿼리를 잘 못치거든요ㅎ...

다만, 위 방식은 mysql에 종속적일 수 밖에 없는데, JPQL로 처리 할 순 없을까요..?

2023-09-14 13:39 UTC, Byeongju-Kong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
> +	ResponseEntity<GohigherResponse<List<KanbanApplicationResponse>>> findForKanban(@Parameter(hidden = true) Long userId);
400번대의 응답이 나가는 경우는 없을까요? 혹시 깜빡하셨을까봐 리마인드 겸 리뷰 남깁니다!

2023-09-14 13:51 UTC, kyukong commented on core-domain/src/main/java/gohigher/application/CurrentProcess.java
> +}
### Projection 을 사용한 이유
필드에 null 이 들어가기 때문에 Projection 을 사용한건 아닙니다! 이미 정의되어 있는 도메인으로 가져왔을 때의 플로우를 생각해보니, 별도의 DTO 를 사용하는 것이 좋겠다는 생각이 들어 적용했습니다. 도메인을 사용하여 칸반 지원서 목록을 구현했을 때의 과정은 다음과 같습니다.

- 사용자 아이디에 해당하는 application 리스트를 조회한다.
- 각각의 application 의 process 리스트에서 currentProcessOrder 에 해당하는 값을 찾는다.
  - application 과 process 는 lazy 로딩으로 구성되어 N+1 이 발생합니다.
  - 현재 프로세스가 아닌 프로세스들도 모두 select 를 거쳐와야 합니다.
- 해당 과정이 리스트 항목당 발생합니다.
  - N+1 이 n 번 발생합니다.

칸반 지원서를 조회하는 API 는 서비스 성격상 매우 자주 호출되는 API 입니다. 하나의 API 에서 발생하는 쿼리문 횟수를 줄이기 위해 Projection 을 적용했습니다.

### View 의존 문제
현재 CurrentProcessDto 는 사용하는 곳이 하나밖에 없어 현재의 API 에 맞는 정보만을 담았습니다. 다만, 현재 프로세스 + 어플리케이션 일부 정보의 형태가 요구되는 API 가 늘어난다면 다음과 같이 대응할 수 있을거라 생각했습니다.

- CurrentProcessDto 의 항목을 늘린다. (+ CurrentProcess)
- Response 객체 생성 시 현재 API 에 해당하는 정보를 추출하여 관리한다.

결국 CurrentProcessDto 를 테이블이 없는 엔티티와 같이 사용하고자 추가했고, 위의 방법대로 간다면 view 의존 문제도 없을거라 생각해서 적용했습니다!

2023-09-14 13:55 UTC, kyukong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +			.toList();
저는 보통 온점으로 분리하는 기준이 1. 가독성 2. 한 줄에 하나의 로직을 담기 위해서 였습니다. 위의 코드에서 list -> entry set -> stream 의 과정이 결국 스트림을 수행하고자 값을 늘어놓는 과정에 불과하고, 가독성 또한 해치치 않는다고 생각해서 한줄로 표현했습니다!

병주님의 코드 정렬 기준도 남겨주시면 감사하겠습니당 🙇🏻‍♀️

2023-09-14 14:15 UTC, Seongwon97 requested changes
유빈님 수고 많으셨습니다!
몇가지 리뷰를 남겼으니 확인 부탁드립니다!

2023-09-14 14:15 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/KanbanApplicationResponse.java
> +				.toList()
메서드를 분리하는 것이 좋을 것 같아요!

2023-09-14 14:15 UTC, Seongwon97 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +		List<KanbanApplicationResponse> response = applicationQueryPort.findForKanban(userId);
변경점이 클 것 같아 리뷰를 남기기가 조금 조심스럽긴한데..개인적으로 Process별로 API를 나눠서 호출하는건 어떨까?하는 생각입니다.

칸반의 프로세스별 지원서가 한 화면에 보여줄 수 있을 만큼만 있다면 하나의 API로 응답을 하는 것이 좋겠지만, 
하나의 프로세스에 한 페이지에서 보여줄 수 없을 정도로 많은 개수의 지원서가 존재한다면 Process내에서도 페이지네이션을 통해 한번에 N개의 데이터들을 반환해야할 것 같다는 생각이에요..!

진짜 과장해서 100개의 지원서가 지원예정에 있다면 그 데이터를 한번에 모두 보여주지는 못하니까요!

2023-09-14 14:15 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/port/in/KanbanApplicationDetailResponse.java
> +		);
매개변수별 줄바꿈은 가독성을 위해서일까요?

2023-09-14 14:15 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +	}
Stream 고수시네요👍

2023-09-14 14:15 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
> +				);
ProcessFixture도 만들어뒀습니다!!!

2023-09-14 14:15 UTC, Seongwon97 commented on core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
> +
Service로직의 주요 동작이 다양한 지원서를 Process별로 나누어서 Response를 만드는 것인데, 해당 로직에 대한 검증이 누락된 것 같아요!

2023-09-14 14:15 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
> +	private Integer currentProcessOrder;
primitive에서 Wrapper class로 변경한 이유가 있을까요?

2023-09-14 14:15 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
> +	)
슬슬 QueryDsl을 적용할때가 온 것 같네요...ㅎ

2023-09-14 14:15 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
> +		class Context_with_user_id {
DCI의 Context는 테스트를 할 때 주어지는 Given상황을 나타내는 것인데 현재는 메서드의 파라미터를 소개하는 것 같습니다.

아래 작성하신 테스트 `@DisplayName("삭제된 어플리케이션이 저장되어 있을 때")`처럼 해당 메서드를 테스트하는 상황을 표현해주는 것이 어떨까요?

2023-09-14 14:15 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
> +			@DisplayName("반환값에 포함되지 않는다")
DisplayName이 최상위 클래스로부터 부자연스럽게 이어집니다!!

`findCurrentProcessByUserId 메서드는` `삭제된 어플리케이션이 저장되어 있을 때`  `반환값에 포함되지 않는다`

DisplayName을 아래와 같이 변경하는 것은 어떨까요?
`findCurrentProcessByUserId 메서드는` `삭제된 어플리케이션을`  `반환값에 포함하지 않는다`

2023-09-14 14:15 UTC, Seongwon97 commented on core-domain/src/main/java/gohigher/application/CurrentProcess.java
> +}
해당 친구는 다른 도메인과 유기적인 관계가 아니라 out-adapter의 응답값으로 사용되는 코드인데, 해당 코드를 유지한다면 `core-domain`이 아닌 `core-application`의 `port.out.persistence`패키지에 `CurrentProcessResponse`와 같은 객체로 만드는 것이 더 적합하다 생각합니다.

2023-09-14 14:49 UTC, kyukong commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
> +	private Integer currentProcessOrder;
그제 정기 회의에서 '지원예정' 에 대해 '프로세스가 없는 경우' 라고 정의하여 null 을 관리하기 위해 변경했습니다!

2023-09-18 13:20 UTC, kyukong commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +			.toList();
일단 반영해뒀습니다~~~ 👍

2023-09-19 06:56 UTC, kyukong commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +		List<KanbanApplicationResponse> response = applicationQueryPort.findForKanban(userId);
네엡.. 좋은 생각이에요 저 개인적으로는 페이징처리가 필요할 정도로 많이 생성되지 않을것같아 고려하지 않았는데, 실제 사용자가 없다보니 판단할 근거가 없어 미리 대비해놓는게 맞는것 같습니다! ㅎㅎ

다만, 설계부터 구현까지 모두 갈아엎어야 하기 때문에 유지보수 하면서 생각해보도록 하겠습니닷!

2023-09-19 11:14 UTC, Byeongju-Kong requested changes

2023-09-19 11:14 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/KanbanApplicationDetailResponse.java
> +	private final String detailedDuty;
혹시
- duty -> position
- detailedDuty -> specificPosition
으로 변경할 수 있을까요?

duty라는게 직무보다는 업무의 느낌이 강해서, 다른 PR에서 위와 같은 네이밍으로 도메인 필드도 변경을 했거든요!

2023-09-19 17:14 UTC, kyukong commented on core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
> +
해당 테스트의 then 부분에 저장한 프로세스 타입을 보유하고 있다는 것으로 테스트했습니다!

2023-09-20 14:43 UTC, shindong96 approved these changes
안녕하세요 유콩! 수고많으셨습니다 :)
크게 RC할 만한 건 보이지 않아 approve할게요!
메서드 네이밍이나 2depth 정도만 고려해봐주세요👍

2023-09-20 14:43 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/KanbanApplicationDetailResponse.java
> +		);
저는 가독성 측면에서 괜찮은 거 같네요 :)

2023-09-20 14:43 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
> +		+ "AND a.currentProcessOrder = p.order "
이렇게 하면 currentProcess 딱 하나만 넣어져서 오나보군요!

2023-09-20 14:43 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
> +			.collect(Collectors.groupingBy(application -> application.getCurrentProcess().getType()));
배워갑니당👍

2023-09-20 14:43 UTC, shindong96 commented on core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
> +			@DisplayName("일정 정보를 반환한다")
각 지원서의 현재 전형 정보를 반환한다는 어떨까요?

2023-09-20 14:43 UTC, shindong96 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
> +					}
2 depth!

2023-09-20 14:43 UTC, shindong96 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
> +	public List<Application> findCurrentProcessByUserId(Long userId) {
Application을 find하는 메서드인데 Process를 가지고 온다는 느낌이 강한거 같아요ㅜ
`findWithCurrentProcessByUserId`나 `findOnlyWithCurrentProcessByUserId`은 어떤가요?

2023-09-21 14:59 UTC, Seongwon97 approved these changes
수고하셨습니다👍

2023-09-21 14:59 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
> +		+ "AND a.currentProcessOrder = p.order "
아주 좋은 방법이군요👍

2023-09-21 14:59 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
> +				entityManager.flush();
save의 경우 flush를 하지 않아도 바로 실행되는 쿼리라 없어도 무방할 것 같습니다.

2023-09-21 14:59 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
> +					() -> assertThat(applicationJpaEntity.getProcesses()).extracting("order", "description")
extracting은 필드를 추출하는 메서드인가요??

2023-09-22 09:30 UTC, kyukong commented on out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
> +					() -> assertThat(applicationJpaEntity.getProcesses()).extracting("order", "description")
넵 리스트로 반한된 값들의 필드를 튜플 형식으로 추출하여 검증할 때 사용합니다!

2023-09-22 09:40 UTC, Byeongju-Kong approved these changes
👍🏻👍🏻👍🏻👍🏻

2023-09-22 09:41 UTC, merged