[FEATURE] 전형일이 작성되어 있지 않은 지원서 목록 조회 API 생성
team-go-higher/backend pull request #95
Opened 2023-09-21 12:30 UTC by kyukong

## 작업 내용
- 캘린더 하단에 띄울 전형일이 작성되어 있지 않은 지원서 목록을 조회하는 API 를 구현한다.
  - 어플리케이션에서 전형일이 작성되어 있지 않은 프로세스가 여러개일 경우 모두 띄운다.
  - 프로세스를 구분하기 위해 Figma 에는 없는 프로세스 정보를 추가하였다.
  - 현재 전형 이전의 프로세스는 의미가 없으므로 결과값에 포함하지 않는다.

resolve #78

2023-09-21 12:37 UTC, kyukong commented on core-application/src/main/java/gohigher/application/port/in/PagingResponse.java
> +	private final List<E> content;
페이징 처리 시 응답값을 통일시키면 좋을것같아 제네릭을 이용했습니다. 네이밍 관련해서 피드백 부탁드립니다.

2023-09-21 12:37 UTC, kyukong commented on core-application/src/main/java/gohigher/pagination/port/in/PagingParameters.java
> +		return PageRequest.of(page - 1, size);
일반적인 페이지는 1부터 시작하지만 MySQL 에서는 0을 기준으로 하기 때문에 -1 을 해주었습니다.

2023-09-21 12:37 UTC, kyukong commented on core-application/src/main/java/gohigher/pagination/port/in/PagingParameters.java
> +public class PagingParameters {
PagingParameters, SliceContainer 는 JpaRepository 를 상속받지 않은 인터페이스에서 Slice 및 Pageable 을 import 할 수 없어 생성한 객체입니다. 헥사고날 구조를 사용하기 때문에 Adapter 를 인터페이스 포트로 관리하는데 사용할 수 없어서 만들었습니다.

처음에는 core-domain 에 두었으나, domain 쪽에 spring data commons 의 의존성을 다루는 것은 역할이 다른것 같아서 core-application 으로 옮겼습니다. 더 좋은 방법이 있다면 피드백 부탁드립니다.

2023-09-25 05:47 UTC, Seongwon97 requested changes
일단 간단하게 core-application모듈에 spring-data의존성이 주입된 것에 대한 개인적인 의견을 위주로 코멘트 남겼습니다!!
테스트부분은 아직 꼼꼼하게 보지 못했는데 추후 다시 확인하고 남겨보겠습니다!

2023-09-25 05:47 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/pagination/port/in/PagingParameters.java
> +public class PagingParameters {
저는 개인적으로 core-application 모듈에는 spring-data 모듈을 제거하는게 좋지 않을까?하는 생각입니다.

현재 구현하신 API는 core-application에서 갖는 관심사는 `전형일이 작성되지 않은 지원서 목록 중에서 N번째 데이터 묶음를 요청하겠다.`라는 관심사만 존재하고 있다고 생각해요.
하지만 현재 Slice와 Pageable을 사용하기 위해 Spring-data 모듈을 추가한 순간 위의 관심사에서 조건이 추가되어 `Spring-data 모듈을 사용하여 전형일이 작성되지 않은 지원서 목록 중에서 N번째 데이터 묶음를 요청하겠다.`로 변경이 됐어요.
이는 Core 로직에 저수준 모듈의 의존도를 더 높이게 되는 것 같아요!

그래서 개인적으로는 spring-data-common의 의존성을 제거하고 서비스에서 Out-adapter로 요청할 때는 Pageable객체를 바로 반환하는 것이 아닌 원하는 페이지 번호와 페이지 사이즈를 반환하는 것이 좋을 것 같습니다!

2023-09-25 05:47 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/pagination/port/in/SliceContainer.java
> +}
core-application는 `Slice`타입의 존재를 알 필요가 없는 것 같아요.
반환값을 out-adapter에서 `List<>`로 변환하고 이후 페이지 요청에 필요한 정보를 해당 컨테이너에 추가해서 반환하는게 좋을 것 같습니다.

2023-09-25 05:47 UTC, Seongwon97 commented on out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
> +		+ "AND a.deleted = false")
오호 JPQL에서도 null을 하면 null 체크가 되나보군요

2023-09-25 05:49 UTC, Seongwon97 commented on core-application/src/main/java/gohigher/pagination/port/in/PagingParameters.java
> +		return PageRequest.of(page - 1, size);
이것만 살펴봐도 페이지를 처리하는 로직에 대한 것은 core-application이 아닌 out-adapter에 위치해야한다 생각합니다!
현재 로직을 살펴보면 spring-data-common뿐만 아니라 MySQL까지 의존해버린 것이니까요!

2023-09-25 05:59 UTC, shindong96 requested changes
수고하셨습니다 유빈님!!
저는 페이지네이션을 잘 몰라서 기본적인 리뷰만 남겼습니다!

2023-09-25 05:59 UTC, shindong96 commented on in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
> +	) {
개행이 좀 어색하네요!

2023-09-25 05:59 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
> +	PagingResponse<EmptyScheduleApplicationResponse> findWithoutSchedule(Long userId, PagingRequest request);
withoutSechedule이라는 말이 스케쥴이 없는 것들을 찾는다기 보다 스케쥴없이 가져온다는 느낌이 나는거 같아요.
`findUnscheduled`과 같은 네이밍은 어떨까요?

2023-09-25 05:59 UTC, shindong96 commented on core-application/src/main/java/gohigher/pagination/port/in/PagingParameters.java
> +		return PageRequest.of(page - 1, size);
이런 이유라면 해당 객체는 sql에 의존적인 객체가 되버리는거 같습니다. -1을 적용하는 것 자체가 mysql때문이니까요.
따라서 해당 부분을 persistence adapter쪽에서 해야할 거 같습니다!

2023-09-25 05:59 UTC, shindong96 commented on core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
> +	SliceContainer<Application> findByUserIdWithoutSchedule(Long userId, PagingParameters pagingParameters);
요기도 네이밍이 unSchedule처럼 있으면 좋을거 같아요!

2023-09-25 06:47 UTC, kyukong commented on core-application/src/main/java/gohigher/application/port/in/PagingResponse.java
> +	private final List<E> content;
# [Discussion ❗️](https://github.com/team-go-higher/backend/discussions/106)

2023-09-25 08:25 UTC, kyukong commented on core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
> +	PagingResponse<EmptyScheduleApplicationResponse> findWithoutSchedule(Long userId, PagingRequest request);
넵 좋습니당 API uri 도 해당 네이밍 따라가겠습니다~!

2023-09-25 09:13 UTC, shindong96 approved these changes
수고하셨습니다!!!!

2023-09-25 09:17 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/pagination/port/in/PagingParameters.java
> +		return PageRequest.of(page - 1, size);
너무 좋은 의견들이네요! 저도 동일하게 생각합니다~!~!

2023-09-25 09:25 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/PagingResponse.java
> +	private final List<E> content;
Discussion에 답글 남겨두었습니다!

2023-09-25 09:28 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/pagination/port/in/PagingParameters.java
> +public class PagingParameters {
저는 선택의 영역이라고 생각해요~! 지금 보니, PagingParameter가 PR에서 삭제가 되었는데요.
Spring Data가 많은 편한 것들을 누리게 해줄 것으로 판단되면 저희가 core에서 `@Transactional`을 사용했던 것 처럼 의존성을 가져가면 될 것 같은데요! 그렇지 않다면 저희가 Core에서 Paging에 관련된 객체들을 만드는 것이 좋을 것 같네요! db out adapter에서 해당 객체의 값으로 Pageable 타입의 객체로 만들고요!

결론적으로, 저는 후자가 좋을 것 같아요! 굳이 의존을 주지 않아도 될 것 같네요!

2023-09-25 09:30 UTC, Byeongju-Kong approved these changes
고생하셨습니다~!~! 다른 분들 리뷰에 comment 몇개와 독자적인 리뷰 남겨뒀어요!

2023-09-25 09:30 UTC, Byeongju-Kong commented on core-application/src/main/java/gohigher/application/port/in/PagingResponse.java
> +	private final List<E> content;
유빈님 그리고 추가적으로 프론트에서 페이징을 어디까지 판단하게 할지 여부를 위해서 lastPage인지에 대한 여부가 응답 값에 있어야 할 것 같네요!

2023-09-25 15:24 UTC, Seongwon97 approved these changes
리뷰 반영 확인했습니다!!
수고하셨습니다👍

2023-09-25 15:24 UTC, Seongwon97 commented on out-adapter-persistence-jpa/build.gradle
> +    implementation 'org.springframework.data:spring-data-commons'
spring-boot-starter-data-jpa를 추가하여 해당 의존은 제거해도 될 것 같습니다!

2023-09-26 10:41 UTC, merged